-- ROLLBACK of 060_money_minor_rename.sql (NOT a numbered migration; docs/MULTI-COUNTRY-DESIGN.md §9 step 6).
--
--   systemctl stop plugsure-api plugsure-gateway
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -1 -f db/rollback/060_down.sql
--   redeploy v1.7.0-rc1 (or v1.6), start gateway then API
--
-- Refuses to run while any row is in a currency other than IDR: such a row has no
-- meaning in a *_idr column (it would be read as rupiah).
DO $$
DECLARE t TEXT; n BIGINT;
BEGIN
  FOREACH t IN ARRAY ARRAY['charging_session','cdr','payment_intent','driver_charge','driver_reservation',
    'reservation_checkout','subscription_plan','subscription_charge','subscription_session','promotion',
    'promotion_redemption','loyalty_program','loyalty_entry','fleet_invoice','fleet_credit_note',
    'commission_statement','commercial_plan']
  LOOP
    EXECUTE format('SELECT count(*) FROM %I WHERE currency <> %L', t, 'IDR') INTO n;
    IF n > 0 THEN RAISE EXCEPTION '060_down: % has % non-IDR row(s); a rollback would read them as rupiah', t, n; END IF;
  END LOOP;
  -- Prices, limits and payment accounts of another country: v1.6 would read them as Indonesian rupiah
  -- (a tariff in RM/kWh, a card limit in sen, a Malaysian site taxed with PPN, a Stripe account as the QRIS acquirer).
  SELECT count(*) INTO n FROM tariff WHERE currency <> 'IDR' OR country_code <> 'ID';
  IF n > 0 THEN RAISE EXCEPTION '060_down: tariff has % non-Indonesian row(s); a rollback would read them as rupiah', n; END IF;
  SELECT count(*) INTO n FROM token WHERE spend_limit_currency <> 'IDR';
  IF n > 0 THEN RAISE EXCEPTION '060_down: token has % spending limit(s) in another currency; a rollback would read them as rupiah', n; END IF;
  SELECT count(*) INTO n FROM site WHERE country_code <> 'ID';
  IF n > 0 THEN RAISE EXCEPTION '060_down: site has % non-Indonesian row(s); v1.6 would rate them as Indonesian', n; END IF;
  SELECT count(*) INTO n FROM integration WHERE archived_at IS NULL AND COALESCE(country_code, 'ID') <> 'ID';
  IF n > 0 THEN RAISE EXCEPTION '060_down: integration has % live account(s) for another country; archive them first', n; END IF;
  IF EXISTS (SELECT 1 FROM ocpi_party GROUP BY org_id HAVING count(*) > 1) THEN
    RAISE EXCEPTION '060_down: an organisation has more than one OCPI party; remove the non-home parties first';
  END IF;
END $$;

DROP INDEX IF EXISTS ocpi_party_home_uq;
ALTER TABLE ocpi_party DROP CONSTRAINT IF EXISTS ocpi_party_pkey;
ALTER TABLE ocpi_party ADD PRIMARY KEY (org_id);

DROP INDEX IF EXISTS commission_statement_period_uq;
CREATE UNIQUE INDEX commission_statement_period_uq
  ON commission_statement (org_id, (COALESCE(owner_id, '00000000-0000-0000-0000-000000000000'::uuid)), period);

DROP INDEX IF EXISTS integration_scope_kind_country_live_uq;
CREATE UNIQUE INDEX integration_scope_kind_live_uq
  ON integration (COALESCE(org_id, '00000000-0000-0000-0000-000000000000'::uuid), kind) WHERE archived_at IS NULL;

-- member_rate back to its 1.6 type (values entered through 1.6 have at most 2 decimals).
ALTER TABLE subscription_plan ALTER COLUMN member_rate TYPE NUMERIC(12,2);

-- generated by tools/codemods/idr-to-minor.mts --sql-down (table, new, old)
DO $$
DECLARE r TEXT[];
BEGIN
  FOREACH r SLICE 1 IN ARRAY ARRAY[
    ARRAY['token', 'spend_limit_minor', 'spend_limit_idr'],
    ARRAY['loyalty_entry', 'value_minor', 'value_idr'],
    ARRAY['loyalty_program', 'point_value_minor', 'point_value_idr'],
    ARRAY['loyalty_program', 'earn_per_1000_minor', 'earn_per_1000_idr'],
    ARRAY['promotion', 'budget_minor', 'budget_idr'],
    ARRAY['promotion_redemption', 'discount_minor', 'discount_idr'],
    ARRAY['subscription_session', 'discount_minor', 'discount_idr'],
    ARRAY['subscription_charge', 'credit_minor', 'credit_idr'],
    ARRAY['subscription_charge', 'total_minor', 'total_idr'],
    ARRAY['subscription_charge', 'tax_minor', 'ppn_idr'],
    ARRAY['subscription_charge', 'tax_base_minor', 'dpp_idr'],
    ARRAY['subscription_charge', 'fee_minor', 'fee_idr'],
    ARRAY['subscription_plan', 'member_rate', 'member_rate_idr'],
    ARRAY['subscription_plan', 'monthly_fee_minor', 'monthly_fee_idr'],
    ARRAY['commission_statement', 'owner_share_minor', 'owner_share_idr'],
    ARRAY['commission_statement', 'total_minor', 'total_idr'],
    ARRAY['commission_statement', 'tax_minor', 'ppn_idr'],
    ARRAY['commission_statement', 'net_minor', 'net_idr'],
    ARRAY['commission_statement', 'mdr_credit_minor', 'mdr_credit_idr'],
    ARRAY['commission_statement', 'private_fee_minor', 'private_fee_idr'],
    ARRAY['commission_statement', 'minimum_topup_minor', 'minimum_topup_idr'],
    ARRAY['commission_statement', 'commission_minor', 'commission_idr'],
    ARRAY['commission_statement', 'gtv_minor', 'gtv_idr'],
    ARRAY['fleet_credit_note', 'total_minor', 'total_idr'],
    ARRAY['fleet_credit_note', 'tax_minor', 'ppn_idr'],
    ARRAY['fleet_credit_note', 'tax_base_minor', 'dpp_idr'],
    ARRAY['fleet_invoice', 'prior_credit_minor', 'prior_credit_idr'],
    ARRAY['fleet_invoice', 'credited_minor', 'credited_idr'],
    ARRAY['fleet_invoice', 'fees_total_minor', 'fees_total_idr'],
    ARRAY['fleet_invoice', 'total_minor', 'total_idr'],
    ARRAY['fleet_invoice', 'roaming_total_minor', 'roaming_total_idr'],
    ARRAY['fleet_invoice', 'own_total_minor', 'own_total_idr'],
    ARRAY['fleet_invoice', 'tax_minor', 'ppn_idr'],
    ARRAY['fleet_invoice', 'tax_base_minor', 'dpp_idr'],
    ARRAY['fleet_invoice', 'taxable_minor', 'tax_base_idr'],
    ARRAY['fleet_invoice', 'local_tax_minor', 'pbjt_idr'],
    ARRAY['fleet_invoice', 'subtotal_minor', 'subtotal_idr'],
    ARRAY['reservation_checkout', 'fee_total_minor', 'fee_total_idr'],
    ARRAY['reservation_checkout', 'fee_tax_minor', 'fee_ppn_idr'],
    ARRAY['reservation_checkout', 'fee_tax_base_minor', 'fee_dpp_idr'],
    ARRAY['reservation_checkout', 'fee_minor', 'fee_idr'],
    ARRAY['driver_reservation', 'fee_total_minor', 'fee_total_idr'],
    ARRAY['driver_reservation', 'fee_tax_minor', 'fee_ppn_idr'],
    ARRAY['driver_reservation', 'fee_tax_base_minor', 'fee_dpp_idr'],
    ARRAY['driver_reservation', 'fee_minor', 'fee_idr'],
    ARRAY['driver_charge', 'amount_minor', 'amount_idr'],
    ARRAY['payment_intent', 'hold_capture_minor', 'hold_capture_idr'],
    ARRAY['payment_intent', 'refunded_minor', 'refunded_idr'],
    ARRAY['payment_intent', 'refund_due_minor', 'refund_due_idr'],
    ARRAY['payment_intent', 'settlement_delta_minor', 'settlement_delta_idr'],
    ARRAY['payment_intent', 'amount_captured_minor', 'amount_captured_idr'],
    ARRAY['payment_intent', 'amount_authorised_minor', 'amount_authorised_idr'],
    ARRAY['charging_session', 'v2x_credit_minor_per_kwh', 'v2x_credit_idr_per_kwh'],
    ARRAY['charging_session', 'prepaid_amount_minor', 'prepaid_amount_idr'],
    ARRAY['site', 'v2x_credit_minor_per_kwh', 'v2x_credit_idr_per_kwh'],
    ARRAY['site', 'reservation_fee_minor', 'reservation_fee_idr'],
    ARRAY['site', 'local_tax_rate_bps', 'pbjt_rate_bps'],
    ARRAY['cdr', 'total_minor', 'total_idr'],
    ARRAY['cdr', 'tax_minor', 'ppn_idr'],
    ARRAY['cdr', 'tax_rate_bps', 'ppn_rate_bps'],
    ARRAY['cdr', 'tax_base_minor', 'ppn_dpp_idr'],
    ARRAY['cdr', 'local_tax_minor', 'pbjt_idr'],
    ARRAY['cdr', 'local_tax_rate_bps', 'pbjt_rate_bps'],
    ARRAY['cdr', 'subtotal_minor', 'subtotal_idr']
  ] LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema() AND table_name = r[1] AND column_name = r[2]) THEN
      EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', r[1], r[2], r[3]);
    END IF;
  END LOOP;
  FOREACH r SLICE 1 IN ARRAY ARRAY[
    ARRAY['site', 'site_v2x_credit_minor_per_kwh_check', 'site_v2x_credit_idr_per_kwh_check'],
    ARRAY['site', 'site_reservation_fee_minor_check', 'site_reservation_fee_idr_check'],
    ARRAY['loyalty_program', 'loyalty_program_point_value_minor_check', 'loyalty_program_point_value_idr_check'],
    ARRAY['loyalty_program', 'loyalty_program_earn_per_1000_minor_check', 'loyalty_program_earn_per_1000_idr_check'],
    ARRAY['subscription_charge', 'subscription_charge_credit_minor_check', 'subscription_charge_credit_idr_check'],
    ARRAY['fleet_credit_note', 'fleet_credit_note_total_minor_check', 'fleet_credit_note_total_idr_check'],
    ARRAY['fleet_credit_note', 'fleet_credit_note_tax_minor_check', 'fleet_credit_note_ppn_idr_check'],
    ARRAY['fleet_credit_note', 'fleet_credit_note_tax_base_minor_check', 'fleet_credit_note_dpp_idr_check'],
    ARRAY['subscription_plan', 'subscription_plan_member_rate_check', 'subscription_plan_member_rate_idr_check'],
    ARRAY['subscription_plan', 'subscription_plan_monthly_fee_minor_check', 'subscription_plan_monthly_fee_idr_check']
  ] LOOP
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = r[2] AND conrelid = r[1]::regclass) THEN
      EXECUTE format('ALTER TABLE %I RENAME CONSTRAINT %I TO %I', r[1], r[2], r[3]);
    END IF;
  END LOOP;
END $$;

DELETE FROM schema_migration WHERE name = '060_money_minor_rename.sql';
