-- 060: amounts are in the row's currency unit (currency_unit.exponent), not rupiah
-- (docs/MULTI-COUNTRY-DESIGN.md §5.3, §5.4). Ships ONLY with the renamed code, in a
-- maintenance window with the API and gateway stopped (§9): v1.6 code cannot run on it.
--
-- Column and constraint renames are catalogue-only (instant). Values are untouched:
-- every existing row is currency 'IDR' (059), whose PlugSure exponent is 0 (whole
-- rupiah), exactly what the *_idr columns held. The RENAME list is generated by
-- `tools/codemods/idr-to-minor.mts --sql` and reviewed by hand; the reverse is
-- db/rollback/060_down.sql.

-- generated by tools/codemods/idr-to-minor.mts --sql (table, old, new); reviewed by hand
DO $$
DECLARE r TEXT[];
BEGIN
  FOREACH r SLICE 1 IN ARRAY ARRAY[
    ARRAY['cdr', 'subtotal_idr', 'subtotal_minor'],
    ARRAY['cdr', 'pbjt_rate_bps', 'local_tax_rate_bps'],
    ARRAY['cdr', 'pbjt_idr', 'local_tax_minor'],
    ARRAY['cdr', 'ppn_dpp_idr', 'tax_base_minor'],
    ARRAY['cdr', 'ppn_rate_bps', 'tax_rate_bps'],
    ARRAY['cdr', 'ppn_idr', 'tax_minor'],
    ARRAY['cdr', 'total_idr', 'total_minor'],
    ARRAY['site', 'pbjt_rate_bps', 'local_tax_rate_bps'],
    ARRAY['site', 'reservation_fee_idr', 'reservation_fee_minor'],
    ARRAY['site', 'v2x_credit_idr_per_kwh', 'v2x_credit_minor_per_kwh'],
    ARRAY['charging_session', 'prepaid_amount_idr', 'prepaid_amount_minor'],
    ARRAY['charging_session', 'v2x_credit_idr_per_kwh', 'v2x_credit_minor_per_kwh'],
    ARRAY['payment_intent', 'amount_authorised_idr', 'amount_authorised_minor'],
    ARRAY['payment_intent', 'amount_captured_idr', 'amount_captured_minor'],
    ARRAY['payment_intent', 'settlement_delta_idr', 'settlement_delta_minor'],
    ARRAY['payment_intent', 'refund_due_idr', 'refund_due_minor'],
    ARRAY['payment_intent', 'refunded_idr', 'refunded_minor'],
    ARRAY['payment_intent', 'hold_capture_idr', 'hold_capture_minor'],
    ARRAY['driver_charge', 'amount_idr', 'amount_minor'],
    ARRAY['driver_reservation', 'fee_idr', 'fee_minor'],
    ARRAY['driver_reservation', 'fee_dpp_idr', 'fee_tax_base_minor'],
    ARRAY['driver_reservation', 'fee_ppn_idr', 'fee_tax_minor'],
    ARRAY['driver_reservation', 'fee_total_idr', 'fee_total_minor'],
    ARRAY['reservation_checkout', 'fee_idr', 'fee_minor'],
    ARRAY['reservation_checkout', 'fee_dpp_idr', 'fee_tax_base_minor'],
    ARRAY['reservation_checkout', 'fee_ppn_idr', 'fee_tax_minor'],
    ARRAY['reservation_checkout', 'fee_total_idr', 'fee_total_minor'],
    ARRAY['fleet_invoice', 'subtotal_idr', 'subtotal_minor'],
    ARRAY['fleet_invoice', 'pbjt_idr', 'local_tax_minor'],
    ARRAY['fleet_invoice', 'tax_base_idr', 'taxable_minor'],
    ARRAY['fleet_invoice', 'dpp_idr', 'tax_base_minor'],
    ARRAY['fleet_invoice', 'ppn_idr', 'tax_minor'],
    ARRAY['fleet_invoice', 'own_total_idr', 'own_total_minor'],
    ARRAY['fleet_invoice', 'roaming_total_idr', 'roaming_total_minor'],
    ARRAY['fleet_invoice', 'total_idr', 'total_minor'],
    ARRAY['fleet_invoice', 'fees_total_idr', 'fees_total_minor'],
    ARRAY['fleet_invoice', 'credited_idr', 'credited_minor'],
    ARRAY['fleet_invoice', 'prior_credit_idr', 'prior_credit_minor'],
    ARRAY['fleet_credit_note', 'dpp_idr', 'tax_base_minor'],
    ARRAY['fleet_credit_note', 'ppn_idr', 'tax_minor'],
    ARRAY['fleet_credit_note', 'total_idr', 'total_minor'],
    ARRAY['commission_statement', 'gtv_idr', 'gtv_minor'],
    ARRAY['commission_statement', 'commission_idr', 'commission_minor'],
    ARRAY['commission_statement', 'minimum_topup_idr', 'minimum_topup_minor'],
    ARRAY['commission_statement', 'private_fee_idr', 'private_fee_minor'],
    ARRAY['commission_statement', 'mdr_credit_idr', 'mdr_credit_minor'],
    ARRAY['commission_statement', 'net_idr', 'net_minor'],
    ARRAY['commission_statement', 'ppn_idr', 'tax_minor'],
    ARRAY['commission_statement', 'total_idr', 'total_minor'],
    ARRAY['commission_statement', 'owner_share_idr', 'owner_share_minor'],
    ARRAY['subscription_plan', 'monthly_fee_idr', 'monthly_fee_minor'],
    ARRAY['subscription_plan', 'member_rate_idr', 'member_rate'],
    ARRAY['subscription_charge', 'fee_idr', 'fee_minor'],
    ARRAY['subscription_charge', 'dpp_idr', 'tax_base_minor'],
    ARRAY['subscription_charge', 'ppn_idr', 'tax_minor'],
    ARRAY['subscription_charge', 'total_idr', 'total_minor'],
    ARRAY['subscription_charge', 'credit_idr', 'credit_minor'],
    ARRAY['subscription_session', 'discount_idr', 'discount_minor'],
    ARRAY['promotion_redemption', 'discount_idr', 'discount_minor'],
    ARRAY['promotion', 'budget_idr', 'budget_minor'],
    ARRAY['loyalty_program', 'earn_per_1000_idr', 'earn_per_1000_minor'],
    ARRAY['loyalty_program', 'point_value_idr', 'point_value_minor'],
    ARRAY['loyalty_entry', 'value_idr', 'value_minor'],
    ARRAY['token', 'spend_limit_idr', 'spend_limit_minor']
  ] LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema() AND table_name = r[1] AND column_name = r[2]) THEN
      EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', r[1], r[2], r[3]);
    END IF;
  END LOOP;
  FOREACH r SLICE 1 IN ARRAY ARRAY[
    ARRAY['subscription_plan', 'subscription_plan_monthly_fee_idr_check', 'subscription_plan_monthly_fee_minor_check'],
    ARRAY['subscription_plan', 'subscription_plan_member_rate_idr_check', 'subscription_plan_member_rate_check'],
    ARRAY['fleet_credit_note', 'fleet_credit_note_dpp_idr_check', 'fleet_credit_note_tax_base_minor_check'],
    ARRAY['fleet_credit_note', 'fleet_credit_note_ppn_idr_check', 'fleet_credit_note_tax_minor_check'],
    ARRAY['fleet_credit_note', 'fleet_credit_note_total_idr_check', 'fleet_credit_note_total_minor_check'],
    ARRAY['subscription_charge', 'subscription_charge_credit_idr_check', 'subscription_charge_credit_minor_check'],
    ARRAY['loyalty_program', 'loyalty_program_earn_per_1000_idr_check', 'loyalty_program_earn_per_1000_minor_check'],
    ARRAY['loyalty_program', 'loyalty_program_point_value_idr_check', 'loyalty_program_point_value_minor_check'],
    ARRAY['site', 'site_reservation_fee_idr_check', 'site_reservation_fee_minor_check'],
    ARRAY['site', 'site_v2x_credit_idr_per_kwh_check', 'site_v2x_credit_minor_per_kwh_check']
  ] LOOP
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = r[2] AND conrelid = r[1]::regclass) THEN
      EXECUTE format('ALTER TABLE %I RENAME CONSTRAINT %I TO %I', r[1], r[2], r[3]);
    END IF;
  END LOOP;
END $$;

-- A member price per kWh is a RATE in major units (RM 0.4550/kWh needs fractions of a
-- sen), not an amount: renamed without a unit suffix and widened to 4 decimals. The
-- table is tiny (one row per plan); the type change rewrites it.
ALTER TABLE subscription_plan ALTER COLUMN member_rate TYPE NUMERIC(14,4);

-- ───────────────────────────── index / key swaps moved here from 059 (v1.6 names them as ON CONFLICT arbiters)

-- One live acquirer integration per (scope, kind, country); NULL country = a legacy Indonesian row.
DROP INDEX IF EXISTS integration_scope_kind_live_uq;
CREATE UNIQUE INDEX IF NOT EXISTS integration_scope_kind_country_live_uq
  ON integration (COALESCE(org_id,'00000000-0000-0000-0000-000000000000'::uuid), kind, COALESCE(country_code,'ID'))
  WHERE archived_at IS NULL;

-- One commission statement per (org, owner, period, currency).
DROP INDEX IF EXISTS commission_statement_period_uq;
CREATE UNIQUE INDEX IF NOT EXISTS commission_statement_period_uq
  ON commission_statement (org_id, (COALESCE(owner_id,'00000000-0000-0000-0000-000000000000'::uuid)), period, currency);

-- OCPI: one party per (organisation, country); is_home marks the eMSP / home identity.
ALTER TABLE ocpi_party DROP CONSTRAINT IF EXISTS ocpi_party_pkey;
ALTER TABLE ocpi_party ADD PRIMARY KEY (org_id, country_code);
CREATE UNIQUE INDEX IF NOT EXISTS ocpi_party_home_uq ON ocpi_party (org_id) WHERE is_home;

COMMENT ON COLUMN cdr.total_minor IS 'Amount in cdr.currency, in currency_unit.exponent units (IDR: whole rupiah; MYR/SGD: sen/cents).';
COMMENT ON COLUMN payment_intent.amount_captured_minor IS 'Amount in payment_intent.currency, in currency_unit.exponent units (IDR: whole rupiah; MYR/SGD: sen/cents).';
COMMENT ON COLUMN subscription_plan.member_rate IS 'Member price per kWh in MAJOR units of subscription_plan.currency (a rate, not an amount).';
