import { type Op, type Param, type Schema, ref, arrayOf, nullable, OK } from '../types.js';

/**
 * Catalogue for src/api/console-routes.ts, from GET /v1/sites to the end of the
 * file (sites, charge point detail and onboarding, configuration, local list,
 * RFID tokens, site tariff assignment, session explorer, DLM priorities and
 * curtailment, firmware, diagnostics and the live OCPP frame stream).
 *
 * Response shapes follow the SQL: snake_case columns stay snake_case, pg NUMERIC
 * comes back as a string unless the code converts it, BIGINT is parsed to a
 * number (db/pool.ts sets an INT8 parser), DATE and TIMESTAMPTZ serialise as
 * ISO date-time strings.
 */

const dt = { type: 'string', format: 'date-time' };
const dtN = nullable('string', { format: 'date-time' });
const strN = nullable('string');
const intN = nullable('integer');
const numN = nullable('number');
const boolN = nullable('boolean');
const uuid = { type: 'string', format: 'uuid' };

// --------------------------------------------------------------- shared params

const identityParam = { identity: 'OCPP identity of the charge point (last path segment of its WebSocket URL), e.g. AUTEL-DC60-SMB-002.' };
const siteIdParam = { siteId: 'Site id (UUID).' };

const sessionFilters: Param[] = [
  { name: 'from', description: 'Sessions that started at or after this instant (any date or date-time Date() can parse).', schema: { type: 'string' } },
  { name: 'to', description: 'Sessions that started before this instant.', schema: { type: 'string' } },
  { name: 'siteId', description: 'Only sessions at this site (UUID).', schema: uuid },
  { name: 'identity', description: 'Only sessions on this charge point (OCPP identity).', schema: { type: 'string' } },
  { name: 'connectorType', description: 'AC or DC (current type), or a plug code such as cCCS2 or sType2.', schema: { type: 'string' } },
  {
    name: 'paymentStatus',
    description: 'Derived payment status.',
    schema: { type: 'string', enum: ['paid', 'invoiced', 'pending', 'unbilled', 'review', 'in_progress', 'failed', 'refunded', 'free', 'held', 'released'] },
  },
  { name: 'state', description: 'Session state (active, ended, rated, settled, disputed).', schema: { type: 'string' } },
  {
    name: 'q',
    description:
      'Session id, OCPP transaction id or card UID. Org-wide users get a substring match on the card UID; site-scoped users only whole-value matches.',
    schema: { type: 'string' },
  },
];

// --------------------------------------------------------------- schemas

const regulatoryFlag: Schema = {
  type: 'object',
  properties: {
    code: { type: 'string' },
    severity: { type: 'string', enum: ['info', 'warning', 'violation'] },
    message: { type: 'string' },
  },
  required: ['code', 'severity', 'message'],
};

export const schemas: Record<string, Schema> = {
  // ------------------------------------------------------------- sites
  SiteComputed: {
    type: 'object',
    description: 'Engineering figures derived from the subscribed capacity and power factor.',
    properties: {
      activePowerCeilingKw: numN,
      crossesTrTmCliff: { type: 'boolean' },
      trTmThresholdKva: { type: 'number' },
      rekeningMinimumKwhPerMonth: { type: 'number', description: '40 hours x kVA per month.' },
    },
    required: ['activePowerCeilingKw', 'crossesTrTmCliff', 'trTmThresholdKva', 'rekeningMinimumKwhPerMonth'],
  },
  SiteListItem: {
    type: 'object',
    properties: {
      id: uuid,
      name: { type: 'string' },
      address: strN,
      city: strN,
      postal_code: strN,
      kabupaten_kota_code: strN,
      lat: numN,
      lon: numN,
      timezone: { type: 'string' },
      grid_tariff_group: strN,
      connected_kva: { ...numN, description: 'Subscribed capacity in kVA (converted to a number).' },
      power_factor: { type: 'number' },
      phases: { type: 'integer' },
      nominal_voltage_v: { type: 'integer' },
      spklu_id: strN,
      spklu_scheme: strN,
      slo_number: strN,
      slo_issuer: strN,
      slo_issued_at: dtN,
      slo_expires_at: dtN,
      pbjt_rate_bps: { type: 'integer' },
      offline_alert_minutes: { ...intN, description: 'Minutes a charger here may be offline before the critical alert; null = the fleet default (OFFLINE_ALERT_MINUTES).' },
      queue_enabled: { type: 'boolean', description: 'The driver queue is on at this site.' },
      queue_offer_minutes: { type: 'integer', description: 'Minutes the next driver has to start once a connector is held for them.' },
      queue_max_length: { type: 'integer', description: 'Most drivers waiting at once.' },
      queue_max_wait_minutes: { type: 'integer', description: 'Longest wait before a place in the queue ends.' },
      reservation_fee_idr: { type: 'integer', description: 'Fee for reserving a connector here in the driver app, before PPN; 0 = free.' },
      v2x_enabled: { type: 'boolean', description: 'Bidirectional charging programme: cars whose drivers agree may give energy back (OCPP 2.1).' },
      v2x_windows: { type: 'array', items: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' } } }, description: 'Local hours when cars may give energy back (HH:MM; to < from wraps midnight).' },
      v2x_max_discharge_w: { type: ['integer', 'null'], description: 'Most the site takes back from cars at once, in W; null = no limit of its own.' },
      v2x_allow_export: { type: 'boolean', description: 'Energy may flow back to the grid. Off: discharge is capped at the site’s own auxiliary load.' },
      v2x_min_soc_percent: { type: 'integer', description: 'Battery floor: no car is discharged below it (a driver may choose a higher one).' },
      v2x_credit_idr_per_kwh: { type: 'integer', description: 'Driver credit per kWh given back, taken off the session before tax.' },
      signed_meter_policy: { type: 'string', enum: ['off', 'record', 'require'], description: 'Signed meter data (OCMF): ignored, kept and checked (default), or required to bill a session.' },
      archived_at: dtN,
      created_at: dt,
      org_name: { type: 'string' },
      ceiling_w: intN,
      reserve_w: intN,
      strategy: strN,
      curtailed: boolN,
      connector_count: { type: 'integer' },
      charging_count: { type: 'integer' },
      faulted_count: { type: 'integer' },
      charger_count: { type: 'integer', description: 'Charge points at the site that are not decommissioned.' },
      online_count: { type: 'integer' },
      managed_ceiling_w: { ...numN, description: 'Configured DLM ceiling, capped at the subscription ceiling.' },
      live_status: { type: 'string', enum: ['empty', 'online', 'offline', 'partial'] },
      computed: ref('SiteComputed'),
      spklu_valid: boolN,
    },
    required: ['id', 'name', 'charger_count', 'online_count', 'live_status', 'computed', 'connector_count'],
  },
  SiteDetail: {
    type: 'object',
    description:
      'The full site row plus its organisation name and power budget. connected_kva and power_factor are Postgres NUMERIC and come back as strings here.',
    properties: {
      id: uuid,
      org_id: uuid,
      name: { type: 'string' },
      address: strN,
      city: strN,
      postal_code: strN,
      kabupaten_kota_code: strN,
      lat: numN,
      lon: numN,
      timezone: { type: 'string' },
      grid_tariff_group: strN,
      connected_kva: { ...strN, description: 'NUMERIC(10,2) as a string, e.g. "197.00".' },
      power_factor: { type: 'string', description: 'NUMERIC(4,3) as a string, e.g. "0.950".' },
      phases: { type: 'integer' },
      nominal_voltage_v: { type: 'integer' },
      spklu_id: strN,
      spklu_scheme: strN,
      slo_number: strN,
      slo_issuer: strN,
      slo_issued_at: dtN,
      slo_expires_at: dtN,
      pbjt_rate_bps: { type: 'integer' },
      offline_alert_minutes: { ...intN, description: 'Minutes a charger here may be offline before the critical alert; null = the fleet default (OFFLINE_ALERT_MINUTES).' },
      queue_enabled: { type: 'boolean', description: 'The driver queue is on at this site.' },
      queue_offer_minutes: { type: 'integer', description: 'Minutes the next driver has to start once a connector is held for them.' },
      queue_max_length: { type: 'integer', description: 'Most drivers waiting at once.' },
      queue_max_wait_minutes: { type: 'integer', description: 'Longest wait before a place in the queue ends.' },
      reservation_fee_idr: { type: 'integer', description: 'Fee for reserving a connector here in the driver app, before PPN; 0 = free.' },
      v2x_enabled: { type: 'boolean', description: 'Bidirectional charging programme: cars whose drivers agree may give energy back (OCPP 2.1).' },
      v2x_windows: { type: 'array', items: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' } } }, description: 'Local hours when cars may give energy back (HH:MM; to < from wraps midnight).' },
      v2x_max_discharge_w: { type: ['integer', 'null'], description: 'Most the site takes back from cars at once, in W; null = no limit of its own.' },
      v2x_allow_export: { type: 'boolean', description: 'Energy may flow back to the grid. Off: discharge is capped at the site’s own auxiliary load.' },
      v2x_min_soc_percent: { type: 'integer', description: 'Battery floor: no car is discharged below it (a driver may choose a higher one).' },
      v2x_credit_idr_per_kwh: { type: 'integer', description: 'Driver credit per kWh given back, taken off the session before tax.' },
      signed_meter_policy: { type: 'string', enum: ['off', 'record', 'require'], description: 'Signed meter data (OCMF): ignored, kept and checked (default), or required to bill a session.' },
      archived_at: dtN,
      created_at: dt,
      billing_model: { type: 'string', enum: ['public', 'private'] },
      owner_id: nullable('string', { format: 'uuid' }),
      previous_owner_id: nullable('string', { format: 'uuid' }),
      roaming_publish: { type: 'boolean' },
      org_name: { type: 'string' },
      ceiling_w: intN,
      reserve_w: intN,
      strategy: strN,
      curtailed: boolN,
      computed: ref('SiteComputed'),
    },
    required: ['computed'],
  },
  SiteInput: {
    type: 'object',
    description:
      'Site fields. On update only the fields sent are changed; an empty string clears a text field. Validation runs at save time.',
    properties: {
      name: { type: 'string', maxLength: 200 },
      address: strN,
      city: strN,
      postalCode: { ...strN, description: '5-digit Indonesian postal code.' },
      kabupatenKotaCode: { ...strN, description: '4-digit BPS kabupaten/kota code, e.g. 3171.' },
      lat: { ...numN, description: 'Latitude within Indonesia (-11.5 to 6.5).' },
      lon: { ...numN, description: 'Longitude within Indonesia (94 to 141.5).' },
      timezone: { type: 'string', enum: ['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura'] },
      gridTariffGroup: { ...strN, description: 'PLN tariff group, e.g. L/TR, L/TM, B-2/TR, B-3/TM, I-3/TM.' },
      connectedKva: { ...numN, description: 'Subscribed capacity in kVA (0 < kVA <= 100000). Above 200 kVA a TR/TM warning is returned.' },
      powerFactor: { type: 'number', minimum: 0.5, maximum: 1 },
      phases: { type: 'integer', enum: [1, 3] },
      nominalVoltageV: { type: 'integer', description: 'Defaults to 230 (1-phase) or 400 (3-phase) when phases is set.' },
      spkluId: { ...strN, description: 'XX.SCHEME.YY.ZZZZ.NNN, e.g. 01.POSO.20.3171.011 (upper-cased).' },
      spkluScheme: { ...strN, description: 'POSO, POPO, PLPO, PLSO, ROSO, ROPO, RLPO, RLSO or RPOO; must match the scheme in spkluId.' },
      sloNumber: strN,
      sloIssuer: strN,
      sloIssuedAt: { ...strN, description: 'YYYY-MM-DD.' },
      sloExpiresAt: { ...strN, description: 'YYYY-MM-DD, after sloIssuedAt.' },
      pbjtRateBps: { type: 'integer', minimum: 0, maximum: 1000, description: 'PBJT-TL rate in basis points (1000 = 10%).' },
      offlineAlertMinutes: { type: ['integer', 'null'], minimum: 1, maximum: 1440, description: 'Minutes a charger here may be offline before the critical "charger offline" alert. Null or empty = the fleet default (OFFLINE_ALERT_MINUTES).' },
      queueEnabled: { type: 'boolean', description: 'Driver queue on or off. Switching it off ends the places of drivers still waiting (they are told).' },
      queueOfferMinutes: { type: 'integer', minimum: 2, maximum: 15, default: 5, description: 'Minutes the next driver has to start once a connector is held for them; not taken in time, they miss their turn.' },
      queueMaxLength: { type: 'integer', minimum: 1, maximum: 200, default: 20, description: 'Most drivers waiting (or holding an offer) at once.' },
      queueMaxWaitMinutes: { type: 'integer', minimum: 15, maximum: 720, default: 120, description: 'Longest wait; a place ends after it.' },
      reservationFeeIdr: { type: 'integer', minimum: 0, maximum: 100000, default: 0, description: 'Fee for reserving a connector here in the driver app, before PPN (added when the operator is PKP). App drivers pay it before the connector is held; a fleet card’s goes on the fleet invoice. Kept once held; not charged when the charger refuses or the driver cancels within 2 minutes. 0 or empty = free.' },
      v2xEnabled: { type: 'boolean', default: false, description: 'Bidirectional charging programme (V2G / V2B). Needs OCPP 2.1 chargers and ISO 15118-20 cars; nothing discharges without the driver’s or the fleet’s consent.' },
      v2xWindows: { anyOf: [{ type: 'array', items: { type: 'object', properties: { from: { type: 'string', pattern: '^([01]\\d|2[0-3]):[0-5]\\d$' }, to: { type: 'string', pattern: '^([01]\\d|2[0-3]):[0-5]\\d$' } }, required: ['from', 'to'] } }, { type: 'string' }], description: 'When cars may give energy back, in local time: [{from, to}] or text such as \"17:00-22:00, 05:00-07:00\". 00:00-00:00 is all day.' },
      v2xMaxDischargeW: { type: ['integer', 'null'], minimum: 1000, description: 'Most the site takes back at once, in W; null for no limit of its own.' },
      v2xAllowExport: { type: 'boolean', default: false, description: 'Let energy flow back to the PLN grid (needs a PLN export agreement). Off: discharge is capped at the auxiliary load set in load management, so it only covers the site’s own use.' },
      v2xMinSocPercent: { type: 'integer', minimum: 10, maximum: 95, default: 40, description: 'Battery floor for every car here.' },
      signedMeterPolicy: { type: 'string', enum: ['off', 'record', 'require'], default: 'record', description: 'Signed meter data (OCMF, from calibration-law meters). record: kept, checked against the connector’s meter key and the bill, problems flagged. require: a session is billed only when its signed start and end readings verify against the registered key and match the bill; otherwise it is parked for review. off: ignored.' },
      v2xCreditIdrPerKwh: { type: 'integer', minimum: 0, maximum: 20000, default: 0, description: 'Driver credit per kWh given back, taken off the session before PBJT-TL and PPN (never below zero). Fixed for a session when the driver agrees.' },
    },
  },
  SiteSaved: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      id: uuid,
      warnings: arrayOf({ type: 'string' }),
    },
    required: ['ok', 'warnings'],
  },

  // ------------------------------------------------------------- charge point detail
  CpDetailConnector: {
    type: 'object',
    properties: {
      id: uuid,
      evse_id: { type: 'integer' },
      connector_id: { type: 'integer' },
      connector_type: strN,
      current_type: { type: 'string' },
      phases: { type: 'integer' },
      max_power_w: { type: 'integer' },
      rated_voltage_v: intN,
      rated_current_a: intN,
      status: { type: 'string' },
      status_updated_at: dtN,
      error_code: strN,
      vendor_error_code: strN,
      status_info: strN,
      meter_serial: strN,
      meter_public_key: { ...strN, description: 'The meter’s public key (hex DER) signed readings are checked against.' },
      meter_accuracy_class: strN,
      tera_type_approval_no: strN,
      tera_last_at: dtN,
      tera_due_at: dtN,
      tera_status: { type: 'string' },
      tera_cert_status: { type: 'string', enum: ['verified', 'pending', 'exempt'] },
      priority: { type: 'integer' },
      maintenance_reason: strN,
      maintenance_since: dtN,
      session_id: nullable('string', { format: 'uuid' }),
      ocpp_transaction_id: strN,
      session_started_at: dtN,
      session_energy_wh: numN,
      session_id_tag: { ...strN, description: 'Card of the active session; masked to the last 4 characters for site-scoped users.' },
    },
    required: ['id', 'evse_id', 'connector_id', 'status'],
  },
  CpDetail: {
    type: 'object',
    properties: {
      id: uuid,
      ocpp_identity: { type: 'string' },
      display_name: strN,
      vendor: strN,
      model: strN,
      serial: strN,
      firmware: strN,
      ocpp_version: strN,
      security_profile: { type: 'integer' },
      has_auth_key: { type: 'boolean' },
      auth_key_rotated_at: dtN,
      key_rotation_days: intN,
      client_cert_fingerprint: strN,
      status: { type: 'string' },
      last_seen_at: dtN,
      last_heartbeat_at: dtN,
      offline_since: dtN,
      boot_count: { type: 'integer' },
      adopted_at: dtN,
      first_seen_at: dtN,
      commissioned_at: dtN,
      decommissioned_at: dtN,
      created_at: dt,
      site_id: uuid,
      site_name: { type: 'string' },
      org_id: uuid,
      timezone: { type: 'string' },
      connectors: arrayOf(ref('CpDetailConnector')),
      online: { type: 'boolean' },
      negotiatedVersion: strN,
      ocppUrl: { type: 'string', description: 'The WebSocket URL the charger should be configured with.' },
    },
    required: ['id', 'ocpp_identity', 'status', 'connectors', 'online', 'negotiatedVersion', 'ocppUrl'],
  },
  CpDetailProfileInput: {
    type: 'object',
    properties: {
      displayName: strN,
      vendor: strN,
      model: strN,
      serial: strN,
      firmware: strN,
      ocppVersion: { type: 'string', enum: ['ocpp1.6', 'ocpp2.0.1', 'ocpp2.1'], description: 'Any value other than ocpp2.0.1 or ocpp2.1 is stored as ocpp1.6.' },
      keyRotationDays: { ...intN, description: 'AuthorizationKey rotation reminder, 7-730 days; null removes it.' },
      siteId: { ...uuid, description: 'Move the charge point to another site of the same organisation.' },
    },
  },

  // ------------------------------------------------------------- EVSE topology
  EvseConnectorSpec: {
    type: 'object',
    properties: {
      connectorId: { type: 'integer', minimum: 1, maximum: 8 },
      connectorType: { type: 'string', enum: ['cCCS2', 'sType2', 'cType2', 'cChaDeMo', 'cGBT', 'sGBT'] },
      currentKind: { type: 'string', enum: ['DC', 'AC3', 'AC1'] },
      maxPowerW: { type: 'number', minimum: 1000, maximum: 1000000, description: 'Nameplate power; AC1 at most 7400 W, AC3 at most 44000 W.' },
      ratedVoltageV: { ...numN, description: '100-1500 V.' },
      ratedCurrentA: { ...numN, description: '1-1000 A.' },
      meterSerial: strN,
      meterPublicKey: { ...strN, description: 'The meter’s public key for signed readings (OCMF): hex DER, base64 or PEM. Omit to keep it; null clears it.' },
      accuracyClass: { ...strN, description: '0.5, 1.0 or 2.0.' },
      typeApprovalNo: strN,
      teraCertStatus: { type: 'string', enum: ['verified', 'pending', 'exempt'], default: 'verified' },
      teraLastAt: { ...strN, description: 'YYYY-MM-DD.' },
      teraDueAt: { ...strN, description: 'YYYY-MM-DD; required when teraCertStatus is verified.' },
    },
    required: ['connectorId', 'connectorType', 'currentKind', 'maxPowerW'],
  },
  EvseSpec: {
    type: 'object',
    properties: {
      evseId: { type: 'integer', minimum: 1, maximum: 128 },
      connectors: arrayOf(ref('EvseConnectorSpec')),
    },
    required: ['evseId', 'connectors'],
  },
  EvseTopology: {
    type: 'object',
    properties: { evses: { ...arrayOf(ref('EvseSpec')), minItems: 1, maxItems: 16 } },
    required: ['evses'],
  },

  // ------------------------------------------------------------- commissioning
  CommissioningStatus: {
    type: 'object',
    properties: {
      identity: { type: 'string' },
      online: { type: 'boolean' },
      status: { type: 'string', description: 'pending_adoption, provisioning, online, offline or decommissioned.' },
      bootCount: { type: 'integer' },
      lastSeenAt: dtN,
      lastBootAt: dtN,
      hardware: {
        type: 'object',
        properties: { vendor: strN, model: strN, firmware: strN, ocppVersion: strN },
      },
      lastAttempt: {
        type: ['object', 'null'],
        description: 'The most recent WebSocket connection attempt. remote_ip is omitted for site-scoped users.',
        properties: {
          ts: dt,
          outcome: { type: 'string' },
          detail: strN,
          tls: { type: 'boolean' },
          auth_present: { type: 'boolean' },
          subprotocols: strN,
          negotiated: strN,
          remote_ip: strN,
        },
      },
      adopted: { type: 'boolean' },
      headline: { type: 'string' },
    },
    required: ['identity', 'online', 'status', 'bootCount', 'lastSeenAt', 'lastBootAt', 'hardware', 'lastAttempt', 'adopted', 'headline'],
  },
  CommissioningConfig: {
    type: 'object',
    properties: {
      format: { type: 'string', const: 'plugsure-commissioning/1' },
      chargePointId: { type: 'string' },
      centralSystemUrl: { type: 'string' },
      ocppVersions: arrayOf({ type: 'string' }),
      securityProfile: { type: 'integer' },
      basicAuth: {
        type: 'object',
        description: 'Present only in the response that issued the key.',
        properties: { username: { type: 'string' }, password: { type: 'string' } },
      },
      heartbeatIntervalS: { type: 'number' },
      generatedAt: dt,
    },
    required: ['format', 'chargePointId', 'centralSystemUrl', 'ocppVersions', 'securityProfile', 'heartbeatIntervalS', 'generatedAt'],
  },
  CommissioningBundle: {
    type: 'object',
    properties: {
      config: ref('CommissioningConfig'),
      json: { type: 'string', description: 'The config pretty-printed as JSON text.' },
      qrDataUrl: { type: 'string', description: 'PNG data: URL of a QR code carrying the config.' },
    },
    required: ['config', 'json', 'qrDataUrl'],
  },
  CommissioningKeysRequest: {
    type: 'object',
    properties: {
      profile: { type: 'integer', enum: [1, 2, 3], default: 2 },
      key: { type: 'string', description: 'Profiles 1-2: your own key, 16-40 letters and digits with at least 8 distinct characters. Omit to generate one.' },
      rotationDays: { type: 'integer', minimum: 7, maximum: 730, description: 'Profiles 1-2: rotation reminder to store with the key.' },
      method: { type: 'string', enum: ['auto', 'csr', 'vault'], description: 'Profile 3: `auto` issues a key and certificate from PlugSure\'s charging-station CA (the key is shown once); `csr` signs the charger\'s own request (`csr`); `vault` issues from Vault PKI.' },
      keyType: { type: 'string', enum: ['ec', 'rsa'], default: 'ec', description: 'Method auto: ECDSA P-256 (recommended) or RSA 2048, whichever the charger supports.' },
      csr: { type: 'string', description: 'Method csr: the charger\'s PKCS#10 request (PEM). Its CN must be the charge point identity.' },
      days: { type: 'integer', minimum: 30, maximum: 3650, description: 'Methods auto and csr: validity in days (default CHARGER_CERT_DAYS, 730).' },
      autoCertificate: { type: 'boolean', description: 'Profile 2: after its first boot the charger is asked for a CSR over OCPP, gets its certificate with CertificateSigned and is moved to Profile 3 (OCPP 1.6 Security Whitepaper chargers).' },
      certificatePem: { type: 'string', description: 'Profile 3: bind this PEM certificate (its SHA-256 fingerprint is stored).' },
      fingerprint: { type: 'string', description: 'Profile 3: bind this SHA-256 fingerprint (64 hex, colons allowed).' },
    },
  },
  CommissioningKeyIssued: {
    type: 'object',
    description: 'Profiles 1 and 2: a new AuthorizationKey.',
    properties: {
      key: { type: 'string', description: 'Plaintext key, shown only in this response.' },
      chargePointId: uuid,
      ocppIdentity: { type: 'string' },
      rotatedAt: dt,
      graceEndsAt: { ...dt, description: 'Until then the previous key is still accepted.' },
      commissioning: ref('CommissioningBundle'),
      warning: { type: 'string' },
    },
    required: ['key', 'chargePointId', 'ocppIdentity', 'rotatedAt', 'graceEndsAt', 'commissioning', 'warning'],
  },
  CommissioningCaBundle: {
    type: 'object',
    description: 'Profile 3 from PlugSure\'s charging-station CA.',
    properties: {
      ok: { type: 'boolean', const: true },
      source: { type: 'string', enum: ['plugsure_ca', 'plugsure_ca_csr'] },
      fingerprint: { type: 'string' }, serialNumber: { type: 'string' }, expiresAt: dt, subject: { type: 'string' }, keyType: { type: 'string' },
      files: {
        type: 'object',
        properties: {
          'client.crt': { type: 'string' },
          'client.key': { type: 'string', description: 'Method auto only: the private key, shown only in this response and not stored.' },
          'ca.pem': { type: 'string', description: 'The charging-station CA.' },
          'chain.pem': { type: 'string', description: 'client.crt followed by the CA.' },
          'csms-root.pem': { type: 'string', description: 'The root of the OCPP host\'s TLS certificate, when configured (CSMS_ROOT_CA_FILE).' },
        },
        required: ['client.crt', 'ca.pem', 'chain.pem'],
      },
      commissioning: ref('CommissioningBundle'),
      warning: { type: 'string' },
    },
    required: ['ok', 'source', 'fingerprint', 'serialNumber', 'expiresAt', 'files', 'commissioning', 'warning'],
  },
  CommissioningVaultBundle: {
    type: 'object',
    description: 'Profile 3 via Vault: a new client certificate and private key.',
    properties: {
      ok: { type: 'boolean', const: true },
      fingerprint: { type: 'string' },
      serialNumber: { type: 'string' },
      expiresAt: dtN,
      files: {
        type: 'object',
        properties: {
          'client.crt': { type: 'string' },
          'client.key': { type: 'string', description: 'Private key, shown only in this response and not stored.' },
          'ca.pem': { type: 'string' },
        },
        required: ['client.crt', 'client.key', 'ca.pem'],
      },
      commissioning: ref('CommissioningBundle'),
      warning: { type: 'string' },
    },
    required: ['ok', 'fingerprint', 'serialNumber', 'expiresAt', 'files', 'commissioning', 'warning'],
  },
  CommissioningCertBound: {
    type: 'object',
    description: 'Profile 3 with your own certificate: the fingerprint now bound (null when the binding was cleared).',
    properties: {
      ok: { type: 'boolean', const: true },
      fingerprint: strN,
      certificate: {
        type: ['object', 'null'],
        properties: {
          subject: { type: 'string' },
          issuer: { type: 'string' },
          validFrom: dt,
          validTo: dt,
          serialNumber: { type: 'string' },
          fingerprint: { type: 'string' },
        },
      },
    },
    required: ['ok', 'fingerprint', 'certificate'],
  },

  // ------------------------------------------------------------- configuration
  ConfigKey: {
    type: 'object',
    properties: {
      key: { type: 'string' },
      value: { ...strN, description: 'Last value read or written; always null for write-only keys.' },
      readonly: { type: 'boolean' },
      rebootRequired: { type: 'boolean' },
      lastStatus: { ...strN, description: 'Result of the last change: Accepted, Rejected, RebootRequired, NotSupported or NoResponse.' },
      readAt: dtN,
      category: { type: 'string', enum: ['Core', 'Smart Charging', 'Security', 'Metrology', 'Networking', 'Local Auth', 'Vendor'] },
      type: { type: 'string', enum: ['integer', 'boolean', 'csl', 'string'] },
      unit: strN,
      description: { type: 'string' },
      managed: { type: 'boolean', description: 'PlugSure provisions this key itself.' },
      writeOnly: { type: 'boolean' },
      reported: { type: 'boolean', description: 'false for catalogue keys the charger has not reported.' },
    },
    required: ['key', 'value', 'readonly', 'rebootRequired', 'lastStatus', 'readAt', 'category', 'type', 'unit', 'description', 'managed', 'writeOnly', 'reported'],
  },
  ConfigView: {
    type: 'object',
    properties: {
      live: { type: 'boolean', description: 'true when the charger answered GetConfiguration during this request.' },
      error: { ...strN, description: 'Why the stored snapshot is shown instead of a live read.' },
      keys: arrayOf(ref('ConfigKey')),
      categories: arrayOf({ type: 'string' }),
    },
    required: ['live', 'error', 'keys', 'categories'],
  },
  ConfigChangeRequest: {
    type: 'object',
    properties: {
      key: { type: 'string', pattern: '^[A-Za-z0-9_.-]{1,50}$' },
      value: { type: 'string' },
    },
    required: ['key'],
  },
  ConfigChangeResult: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', description: 'true when the charger answered Accepted or RebootRequired.' },
      status: { type: 'string', description: 'Accepted, Rejected, RebootRequired, NotSupported, or NoResponse.' },
      rebootRequired: { type: 'boolean' },
    },
    required: ['ok', 'status', 'rebootRequired'],
  },

  // ------------------------------------------------------------- local list
  LocalListSyncResult: {
    type: 'object',
    properties: {
      ok: { type: 'boolean' },
      identity: { type: 'string' },
      status: { type: 'string', description: 'SendLocalList answer from the charger.' },
      version: { type: 'integer', description: 'List version sent (charger version + 1).' },
      count: { type: 'integer', description: 'Cards sent.' },
      error: { type: 'string', description: 'Present when ok is false because the charger could not be reached or does not support a local list.' },
    },
    required: ['ok', 'identity'],
  },
  LocalListSiteSyncResult: {
    type: 'object',
    properties: { results: arrayOf(ref('LocalListSyncResult')) },
    required: ['results'],
  },

  // ------------------------------------------------------------- tokens
  Token: {
    type: 'object',
    properties: {
      id: uuid,
      uid: { type: 'string' },
      kind: { type: 'string' },
      status: { type: 'string' },
      valid_to: dtN,
      offline_allowed: { type: 'boolean' },
      holder_name: strN,
      holder_phone: strN,
      account_type: { type: 'string', enum: ['retail', 'fleet', 'vip', 'technician'] },
      fleet_name: strN,
      energy_limit_wh: numN,
      spend_limit_idr: numN,
      notes: strN,
      created_at: dt,
      updated_at: dt,
      has_pin: { type: 'boolean' },
      lifetime_energy_wh: { type: 'number' },
      total_sessions: { type: 'integer' },
      lifetime_spend_idr: { type: 'number' },
      last_used_at: dtN,
    },
    required: ['id', 'uid', 'status', 'account_type', 'has_pin', 'lifetime_energy_wh', 'total_sessions', 'lifetime_spend_idr'],
  },
  TokenUnknownTag: {
    type: 'object',
    properties: {
      id_tag: { type: 'string' },
      last_seen_at: dt,
      ocpp_identity: { type: 'string', description: 'Charger where the card was presented most recently.' },
      presentations: { type: 'integer' },
    },
    required: ['id_tag', 'last_seen_at', 'ocpp_identity', 'presentations'],
  },
  TokenInput: {
    type: 'object',
    properties: {
      uid: { type: 'string', pattern: '^[\\x21-\\x7e]{1,20}$', description: 'Card UID (OCPP idTag). Required on create, ignored on update. Pure hex is upper-cased.' },
      holderName: strN,
      holderPhone: strN,
      accountType: { type: 'string', enum: ['retail', 'fleet', 'vip', 'technician'], description: 'Defaults to retail on create.' },
      fleetName: strN,
      status: { type: 'string', enum: ['Accepted', 'Blocked', 'Expired'], description: 'Defaults to Accepted on create.' },
      validTo: { ...strN, description: 'Expiry date or date-time.' },
      energyLimitKwh: { ...numN, description: 'Lifetime energy cap in kWh (stored in Wh).' },
      spendLimitIdr: { ...numN, description: 'Lifetime spend cap in IDR.' },
      offlineAllowed: { type: 'boolean' },
      notes: strN,
      pin: { ...strN, description: '4-8 digit PIN for the driver app; stored hashed. null removes it.' },
    },
  },
  TokenCreated: {
    type: 'object',
    properties: { ok: { type: 'boolean', const: true }, id: uuid, uid: { type: 'string' } },
    required: ['ok', 'id', 'uid'],
  },
  TokenUpdated: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      hint: { type: 'string', description: 'Present when the status changed: push the local list so offline chargers learn it.' },
    },
    required: ['ok'],
  },

  // ------------------------------------------------------------- tariff assignment
  TariffAssignmentRequest: {
    type: 'object',
    properties: {
      tariffId: uuid,
      priority: { type: 'integer', default: 0 },
      currentType: { type: 'string', enum: ['AC', 'DC'], description: 'Apply only to AC or DC connectors; omit for all.' },
    },
    required: ['tariffId'],
  },
  TariffAssignmentFlag: regulatoryFlag,
  TariffAssignmentResult: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      flags: arrayOf(ref('TariffAssignmentFlag')),
    },
    required: ['ok', 'flags'],
  },

  // ------------------------------------------------------------- sessions
  SessionSearchBreakdown: {
    type: 'object',
    properties: {
      energySubtotalIdr: numN,
      serviceFeeIdr: numN,
      idleFeeIdr: numN,
      pbjtIdr: numN,
      dppIdr: numN,
      ppnIdr: numN,
      mdrIdr: { type: 'number', description: 'Estimated QRIS MDR (operator cost, not charged to the driver); 0 for other methods.' },
      grossTotalIdr: numN,
    },
    required: ['energySubtotalIdr', 'serviceFeeIdr', 'idleFeeIdr', 'pbjtIdr', 'dppIdr', 'ppnIdr', 'mdrIdr', 'grossTotalIdr'],
  },
  SessionSearchRow: {
    type: 'object',
    properties: {
      id: uuid,
      started_at: dt,
      ended_at: dtN,
      state: { type: 'string' },
      energy_wh: { type: 'number' },
      duration_s: intN,
      stop_reason: strN,
      meter_start_wh: { type: 'number' },
      meter_stop_wh: numN,
      ocpp_transaction_id: strN,
      needs_review: { type: 'boolean' },
      review_reason: strN,
      idle_minutes: { type: 'integer' },
      payment_mode: strN,
      prepaid_amount_idr: intN,
      ocpp_identity: { type: 'string' },
      display_name: strN,
      evse_no: { type: 'integer' },
      connector_type: strN,
      current_type: { type: 'string' },
      site_id: uuid,
      site_name: { type: 'string' },
      id_tag: { ...strN, description: 'Masked to the last 4 characters for site-scoped users.' },
      holder_name: { ...strN, description: 'Always null for site-scoped users.' },
      cdr_id: nullable('string', { format: 'uuid' }),
      subtotal_idr: intN,
      pbjt_idr: intN,
      pbjt_rate_bps: intN,
      ppn_dpp_idr: intN,
      ppn_rate_bps: intN,
      ppn_idr: intN,
      total_idr: intN,
      regulatory_flags: { type: ['array', 'null'] },
      issued_at: dtN,
      payment_method: strN,
      payment_state: strN,
      payment_status: { type: 'string' },
      breakdown: ref('SessionSearchBreakdown'),
    },
    required: ['id', 'started_at', 'state', 'energy_wh', 'ocpp_identity', 'site_id', 'payment_status', 'breakdown'],
  },
  SessionSearchResult: {
    type: 'object',
    properties: {
      rows: arrayOf(ref('SessionSearchRow')),
      totals: {
        type: 'object',
        description: 'Totals over every session matching the filter, not just this page.',
        properties: {
          sessions: { type: 'integer' },
          energy_wh: { type: 'number' },
          revenue_idr: { type: 'number' },
          pbjt_idr: { type: 'number' },
          ppn_idr: { type: 'number' },
        },
        required: ['sessions', 'energy_wh', 'revenue_idr', 'pbjt_idr', 'ppn_idr'],
      },
      limit: { type: 'integer' },
      offset: { type: 'integer' },
    },
    required: ['rows', 'totals', 'limit', 'offset'],
  },

  // ------------------------------------------------------------- load management
  CurtailPriorityList: {
    type: 'object',
    properties: {
      priorities: arrayOf({
        type: 'object',
        properties: {
          connectorUuid: uuid,
          priority: { type: 'integer', minimum: -100, maximum: 100, default: 0, description: 'Higher wins under the priority strategy; clamped to -100..100.' },
        },
        required: ['connectorUuid'],
      }),
    },
  },
  CurtailRequest: {
    type: 'object',
    properties: {
      curtailed: { type: 'boolean', description: 'true to curtail the site to 0 W; false (or omitted) lifts the curtailment.' },
      reason: { type: 'string', maxLength: 200, description: 'Defaults to "Genset / grid outage" when curtailing.' },
    },
  },
  CurtailResult: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      curtailed: { type: 'boolean' },
      dispatch: { type: 'string', const: 'started' },
    },
    required: ['ok', 'curtailed', 'dispatch'],
  },

  // ------------------------------------------------------------- firmware
  FirmwareImage: {
    type: 'object',
    properties: {
      id: uuid,
      name: { type: 'string' },
      version: { type: 'string' },
      vendor: strN,
      compatible_models: arrayOf({ type: 'string' }),
      source: { type: 'string', enum: ['upload', 'url'] },
      url: strN,
      file_name: strN,
      size_bytes: numN,
      sha256: strN,
      sha256_verified: { type: 'boolean' },
      notes: strN,
      created_by: strN,
      created_at: dt,
      archived_at: dtN,
      campaigns: { type: 'integer', description: 'Campaigns that use this image.' },
    },
    required: ['id', 'name', 'version', 'compatible_models', 'source', 'sha256_verified', 'created_at', 'campaigns'],
  },
  FirmwareImageUrlRequest: {
    type: 'object',
    properties: {
      name: { type: 'string', maxLength: 200 },
      version: { type: 'string', maxLength: 100, description: 'The version string the charger will report after the update.' },
      url: { type: 'string', pattern: '^https://', description: 'Public HTTPS download URL; private and internal addresses are refused.' },
      vendor: { type: 'string' },
      compatibleModels: {
        description: 'Model names (substring match, case-insensitive) a campaign may target; array or comma-separated string, at most 50.',
        anyOf: [arrayOf({ type: 'string' }), { type: 'string' }],
      },
      sha256: { type: 'string', description: 'Declared SHA-256 (64 hex characters).' },
      notes: { type: 'string', maxLength: 2000 },
    },
    required: ['name', 'version', 'url'],
  },
  FirmwareImageCreated: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      id: uuid,
      sha256: { type: 'string', description: 'Upload only: SHA-256 of the stored file.' },
      size: { type: 'integer', description: 'Upload only: bytes stored.' },
    },
    required: ['ok', 'id'],
  },
  FirmwareVerifyResult: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      sha256: { type: 'string' },
      size: { type: 'integer' },
    },
    required: ['ok', 'sha256', 'size'],
  },

  // ------------------------------------------------------------- campaigns
  CampaignSummary: {
    type: 'object',
    properties: {
      id: uuid,
      name: { type: 'string' },
      status: { type: 'string', enum: ['scheduled', 'running', 'completed', 'cancelled'] },
      target_type: { type: 'string', enum: ['charge_point', 'site', 'fleet'] },
      window_start: strN,
      window_end: strN,
      max_retries: { type: 'integer' },
      retry_interval_s: { type: 'integer' },
      created_by: strN,
      created_at: dt,
      completed_at: dtN,
      image_name: { type: 'string' },
      image_version: { type: 'string' },
      jobs: { type: 'integer' },
      verified: { type: 'integer' },
      failed: { type: 'integer' },
      pending: { type: 'integer' },
    },
    required: ['id', 'name', 'status', 'target_type', 'image_name', 'image_version', 'jobs', 'verified', 'failed', 'pending'],
  },
  CampaignRequest: {
    type: 'object',
    properties: {
      imageId: uuid,
      name: { type: 'string' },
      targetType: { type: 'string', enum: ['charge_point', 'site', 'fleet'] },
      targetIds: { ...arrayOf(uuid), description: 'Charge point ids or site ids (UUIDs); not used for fleet. Non-UUID entries are dropped.' },
      windowStart: { ...strN, description: 'HH:MM local site time; set both ends or neither.' },
      windowEnd: { ...strN, description: 'HH:MM local site time.' },
      maxRetries: { type: 'integer', minimum: 0, maximum: 10, default: 3 },
      retryIntervalS: { type: 'integer', minimum: 60, maximum: 86400, default: 600 },
    },
    required: ['imageId', 'name', 'targetType'],
  },
  CampaignCreated: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      id: uuid,
      targets: { type: 'integer', description: 'Charge points a job was created for.' },
    },
    required: ['ok', 'id', 'targets'],
  },
  CampaignJob: {
    type: 'object',
    properties: {
      id: uuid,
      state: { type: 'string' },
      attempts: { type: 'integer' },
      last_error: strN,
      next_attempt_at: dtN,
      dispatched_at: dtN,
      updated_at: dt,
      firmware_before: strN,
      ocpp_identity: { type: 'string' },
      firmware_now: strN,
      model: strN,
      site_name: { type: 'string' },
      online: { type: 'boolean' },
      stage: { type: 'integer', minimum: -1, maximum: 5, description: 'Index into stages; -1 before dispatch or after failure.' },
    },
    required: ['id', 'state', 'attempts', 'ocpp_identity', 'online', 'stage'],
  },
  CampaignDetail: {
    type: 'object',
    properties: {
      campaign: {
        type: 'object',
        properties: {
          id: uuid,
          org_id: uuid,
          image_id: uuid,
          name: { type: 'string' },
          target_type: { type: 'string' },
          target_ids: arrayOf({ type: 'string' }),
          window_start: strN,
          window_end: strN,
          max_retries: { type: 'integer' },
          retry_interval_s: { type: 'integer' },
          status: { type: 'string' },
          created_by: strN,
          created_at: dt,
          completed_at: dtN,
          image_name: { type: 'string' },
          image_version: { type: 'string' },
        },
        required: ['id', 'name', 'status', 'image_name', 'image_version'],
      },
      jobs: arrayOf(ref('CampaignJob')),
      stages: arrayOf({ type: 'string' }),
    },
    required: ['campaign', 'jobs', 'stages'],
  },

  // ------------------------------------------------------------- diagnostics
  DiagnosticsRequestRow: {
    type: 'object',
    properties: {
      id: uuid,
      status: { type: 'string', description: 'Requested, Uploading, Uploaded, UploadFailed, Rejected or Idle.' },
      start_time: dtN,
      stop_time: dtN,
      location: { type: 'string' },
      file_name: strN,
      size_bytes: numN,
      requested_by: strN,
      requested_at: dt,
      updated_at: dt,
      has_file: { type: 'boolean' },
      builtin: { type: 'boolean', description: 'The built-in one-time upload receiver was used.' },
      ocpp_identity: { type: 'string' },
    },
    required: ['id', 'status', 'location', 'requested_at', 'has_file', 'builtin', 'ocpp_identity'],
  },
  DiagnosticsRequestBody: {
    type: 'object',
    properties: {
      startTime: { type: 'string', format: 'date-time', description: 'Oldest log entry wanted.' },
      stopTime: { type: 'string', format: 'date-time', description: 'Newest log entry wanted.' },
      location: {
        type: 'string',
        description: 'Your own ftp://, ftps://, sftp:// or http(s):// upload location. Omit to use the built-in receiver (needs PUBLIC_BASE_URL or a reachable request origin).',
      },
    },
  },
  DiagnosticsRequested: {
    type: 'object',
    properties: {
      ok: { type: 'boolean', const: true },
      id: uuid,
      fileName: strN,
      location: { type: 'string' },
    },
    required: ['ok', 'id', 'fileName', 'location'],
  },
  DiagnosticsContent: {
    type: 'object',
    properties: {
      available: { type: 'boolean' },
      fileName: strN,
      binary: { type: 'boolean' },
      text: { ...strN, description: 'Log text (gzip is unpacked), first 2 MiB; null for binary files.' },
      truncated: { type: 'boolean' },
      note: strN,
    },
    required: ['available'],
  },
};

// --------------------------------------------------------------- operations

export const ops: Op[] = [
  // ============================================================= sites
  {
    method: 'GET',
    path: '/v1/sites',
    tag: 'Sites',
    summary: 'List sites',
    description:
      'Returns every site of your organisation that you can read, active sites first, with live charger counts and the managed DLM ceiling. Site-scoped users see only their sites. Archived sites are included, with archived_at set.',
    responses: { 200: { description: 'Sites.', schema: arrayOf(ref('SiteListItem')) } },
  },
  {
    method: 'GET',
    path: '/v1/sites/:siteId',
    tag: 'Sites',
    summary: 'Get a site',
    description: 'Returns the full site record, its power budget and the derived engineering figures.',
    pathParams: siteIdParam,
    responses: { 200: { description: 'The site.', schema: ref('SiteDetail') } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/sites',
    tag: 'Sites',
    summary: 'Create a site',
    description:
      'Creates a site after validating it against PLN and regulatory rules; invalid input is refused with 422 (the body lists every field error and the warnings). When connectedKva is given, a load-management budget at the subscription ceiling is created too. Audited as site.created.',
    body: {
      required: true,
      schema: { ...ref('SiteInput'), required: ['name'] } as Schema,
      example: {
        name: 'SPKLU Thamrin City',
        address: 'Jl. Kebon Kacang Raya No. 1, Tanah Abang',
        city: 'Jakarta Pusat',
        postalCode: '10230',
        kabupatenKotaCode: '3171',
        lat: -6.1965,
        lon: 106.8185,
        timezone: 'Asia/Jakarta',
        gridTariffGroup: 'L/TR',
        connectedKva: 197,
        powerFactor: 0.95,
        phases: 3,
        spkluId: '01.POSO.20.3171.011',
        spkluScheme: 'POSO',
        sloNumber: 'SLO-3171-2026-00421',
        sloIssuer: 'PT Sertifikasi Kelistrikan Nusantara',
        sloIssuedAt: '2026-02-10',
        sloExpiresAt: '2031-02-10',
        pbjtRateBps: 300,
      },
    },
    responses: { 200: { description: 'Created.', schema: ref('SiteSaved') } },
    errors: [422],
  },
  {
    method: 'PUT',
    path: '/v1/sites/:siteId',
    tag: 'Sites',
    summary: 'Update a site',
    description:
      'Changes only the fields sent; validation runs against the merged record and refuses invalid input with 422. When the subscribed capacity or power factor drops, a stored DLM ceiling above the new subscription ceiling is lowered to it. Audited as site.updated.',
    pathParams: siteIdParam,
    body: {
      required: true,
      schema: ref('SiteInput'),
      example: { connectedKva: 131, gridTariffGroup: 'L/TR', pbjtRateBps: 300 },
    },
    responses: { 200: { description: 'Updated.', schema: ref('SiteSaved') } },
    errors: [404, 422],
  },
  {
    method: 'POST',
    path: '/v1/sites/:siteId/archive',
    tag: 'Sites',
    summary: 'Archive a site',
    description:
      'Marks the site archived. Refused with 400 while the site still has charge points that are not decommissioned. Audited as site.archived.',
    pathParams: siteIdParam,
    responses: { 200: { description: 'Archived.', schema: OK } },
    errors: [400, 404],
  },
  {
    method: 'GET',
    path: '/v1/sites/:siteId/queue',
    tag: 'Sites',
    summary: "The site's driver queue",
    description:
      "The queue policy (queueEnabled and friends on the site), then every driver waiting or holding an offer, in order, and the places that ended in the last 24 hours (served, missed, left, expired, removed). Drivers are shown as a masked phone number or their fleet card. waiting drivers have a position: 1 + the drivers ahead of them who could take a connector they could. stats.medianWaitMinutes is the median time from joining to the offer for drivers served in the last 24 hours.",
    pathParams: siteIdParam,
    responses: { 200: { description: 'The queue.', schema: { type: 'object', required: ['settings', 'entries', 'stats'], properties: {
      settings: { type: 'object', properties: { enabled: { type: 'boolean' }, offerMinutes: { type: 'integer' }, maxLength: { type: 'integer' }, maxWaitMinutes: { type: 'integer' } } },
      entries: { type: 'array', items: { type: 'object', properties: {
        id: uuid, state: { type: 'string', enum: ['waiting', 'offered', 'served', 'left', 'missed', 'expired', 'removed'] },
        joinedAt: dt, offeredAt: dtN, endedAt: dtN, endReason: strN, position: intN,
        driver: { type: 'string' }, want: { type: 'string', description: 'AC or DC and a plug type, or "Any connector".' },
        offer: { type: ['object', 'null'], properties: { connector: { type: 'string' }, expiresAt: dt } },
      } } },
      stats: { type: 'object', properties: { waiting: { type: 'integer' }, offered: { type: 'integer' }, served24h: { type: 'integer' }, missed24h: { type: 'integer' }, left24h: { type: 'integer' }, medianWaitMinutes: intN } },
    } } } },
    errors: [404],
  },
  {
    method: 'DELETE',
    path: '/v1/sites/:siteId/queue/:entryId',
    tag: 'Sites',
    summary: 'Remove a driver from the queue',
    description:
      'Ends a waiting place, or an offer (the connector held for the driver is released with CancelReservation and goes to the next driver). The driver gets a push notification. Audited as driver_queue.removed.',
    pathParams: { ...siteIdParam, entryId: 'The queue place (UUID).' },
    responses: { 200: { description: 'Removed.', schema: OK } },
    errors: [404],
  },

  // ============================================================= charge points
  {
    method: 'GET',
    path: '/v1/charge-points/:identity',
    tag: 'Chargers',
    summary: 'Get a charge point',
    description:
      'Returns the charge point, its site, security state, every connector with any active session, live connection state and the OCPP URL to configure on the unit. Site-scoped users see the active session card masked to the last 4 characters.',
    pathParams: identityParam,
    responses: { 200: { description: 'The charge point.', schema: ref('CpDetail') } },
    errors: [404],
  },
  {
    method: 'PUT',
    path: '/v1/charge-points/:identity',
    tag: 'Chargers',
    summary: 'Update a charge point profile',
    description:
      'Changes only the fields sent (text fields are cut to 200 characters). Moving to another site needs charge_point:write at the target site and is limited to sites of the same organisation. Audited as charge_point.updated.',
    pathParams: identityParam,
    body: {
      required: true,
      schema: ref('CpDetailProfileInput'),
      example: {
        displayName: 'DC 60 kW — Basement B1 Bay 2',
        vendor: 'Autel Energy',
        model: 'MaxiCharger DC Fast 60',
        serial: 'AUTEL-DC60-SMB-002',
        ocppVersion: 'ocpp1.6',
        keyRotationDays: 180,
      },
    },
    responses: { 200: { description: 'Updated.', schema: OK } },
    errors: [400, 404],
  },
  {
    method: 'PUT',
    path: '/v1/charge-points/:identity/evses',
    tag: 'Chargers',
    summary: 'Set the EVSE and connector topology',
    description:
      'Creates or updates EVSEs and connectors with nameplate and metrology data; nothing is deleted, because sessions reference connectors. On OCPP 1.6 each EVSE may have only one connector (a second gun is a second EVSE). Invalid topologies are refused with 422 listing every problem. Audited as charge_point.topology_changed.',
    pathParams: identityParam,
    body: {
      required: true,
      schema: ref('EvseTopology'),
      example: {
        evses: [
          {
            evseId: 1,
            connectors: [
              {
                connectorId: 1,
                connectorType: 'cCCS2',
                currentKind: 'DC',
                maxPowerW: 60000,
                ratedVoltageV: 1000,
                ratedCurrentA: 150,
                meterSerial: 'LEM-DCBM-2204118',
                accuracyClass: '0.5',
                typeApprovalNo: 'UTTP-KWH-2025-0193',
                teraCertStatus: 'verified',
                teraLastAt: '2026-03-02',
                teraDueAt: '2027-03-02',
              },
            ],
          },
          {
            evseId: 2,
            connectors: [{ connectorId: 1, connectorType: 'cChaDeMo', currentKind: 'DC', maxPowerW: 50000, teraCertStatus: 'pending' }],
          },
        ],
      },
    },
    responses: { 200: { description: 'Saved.', schema: OK } },
    errors: [404, 422],
  },

  // ============================================================= onboarding
  {
    method: 'GET',
    path: '/v1/charge-points/:identity/commissioning',
    tag: 'Onboarding',
    summary: 'Get commissioning status',
    description:
      'What the onboarding wizard polls while it waits for a unit: whether it is connected, has booted and been adopted, and the outcome of its last connection attempt (a refused handshake explains most commissioning failures). Site-scoped users get no source IP and no attempt from before the charger joined their site.',
    pathParams: identityParam,
    responses: { 200: { description: 'Commissioning status.', schema: ref('CommissioningStatus') } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/decommission',
    tag: 'Onboarding',
    summary: 'Decommission a charge point',
    description:
      'Sets the status to decommissioned and clears its AuthorizationKey (current and previous) and client-certificate binding, so it can no longer connect. Refused with 400 while a session is in progress. The optional reason is recorded in the audit entry charge_point.decommissioned.',
    pathParams: identityParam,
    body: {
      required: false,
      schema: { type: 'object', properties: { reason: { type: 'string' } } },
      example: { reason: 'Unit replaced after flood damage' },
    },
    responses: { 200: { description: 'Decommissioned.', schema: OK } },
    errors: [400, 404],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/reinstate',
    tag: 'Onboarding',
    summary: 'Reinstate a decommissioned charge point',
    description:
      'Returns a decommissioned unit to pending_adoption with security profile 0, so it goes through adoption again and needs new credentials. Has no effect on a unit that is not decommissioned, but still answers ok. Audited as charge_point.reinstated.',
    pathParams: identityParam,
    responses: { 200: { description: 'Reinstated.', schema: OK } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/keys',
    tag: 'Onboarding',
    summary: 'Provision charger security credentials',
    description:
      'Profiles 1-2 issue a new AuthorizationKey (generated, or your own) and return it with a commissioning export; the key is shown once and the previous key stays valid for a grace window. Profile 3 issues a client certificate automatically from PlugSure\'s charging-station CA (method "auto": key and certificate, the key shown once and not stored; method "csr": the charger\'s own request signed), issues one from Vault PKI (method "vault"), or binds your certificate PEM or fingerprint; with neither, the binding is cleared. This does not raise the security profile: configure the credential on the charger first, then raise the profile. Vault errors return 501 (not configured) or 502.',
    pathParams: identityParam,
    body: {
      required: false,
      schema: ref('CommissioningKeysRequest'),
      example: { profile: 2, rotationDays: 180 },
    },
    responses: {
      200: {
        description: 'The issued key, certificate bundle or binding, depending on the profile.',
        schema: { anyOf: [ref('CommissioningKeyIssued'), ref('CommissioningCaBundle'), ref('CommissioningVaultBundle'), ref('CommissioningCertBound')] },
      },
    },
    errors: [400, 404, 422, 501, 502],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/client-certificate/vault',
    tag: 'Onboarding',
    summary: 'Issue a client certificate from Vault',
    description:
      'Issues a Security Profile 3 client certificate for the charger from Vault PKI, binds its fingerprint and returns the certificate, private key and CA chain with a commissioning export. The private key is shown once and is not stored. Returns 501 when Vault is not configured and 502 when Vault fails. Audited as charge_point.client_cert.issued.',
    pathParams: identityParam,
    responses: { 200: { description: 'The certificate bundle.', schema: ref('CommissioningVaultBundle') } },
    errors: [400, 404, 501, 502],
    permissions: ['charge_point:write'],
  },
  {
    method: 'GET',
    path: '/v1/charge-points/:identity/commissioning-export',
    tag: 'Onboarding',
    summary: 'Get the commissioning export',
    description:
      'Returns the configuration a technician sets on the charger (OCPP URL, versions, security profile, heartbeat) as JSON and as a QR code. It never contains the AuthorizationKey, which is shown only when issued.',
    pathParams: identityParam,
    responses: { 200: { description: 'The commissioning export.', schema: ref('CommissioningBundle') } },
    errors: [404],
  },

  // ============================================================= configuration
  {
    method: 'GET',
    path: '/v1/charge-points/:identity/config',
    tag: 'Configuration',
    summary: 'Get configuration keys',
    description:
      'Reads the configuration live from the charger (GetConfiguration) and stores it, then returns every reported key plus catalogue keys the charger did not report. Live reads need charge_point:config or charge_point:command; otherwise, when the charger is offline or does not answer, the stored snapshot is returned with error set. Write-only keys never have a value.',
    pathParams: identityParam,
    query: [
      { name: 'refresh', description: 'Send 0 to skip the live read and return the stored snapshot.', schema: { type: 'string', enum: ['0', '1'], default: '1' } },
    ],
    responses: { 200: { description: 'Configuration keys.', schema: ref('ConfigView') } },
    errors: [404],
  },
  {
    method: 'PUT',
    path: '/v1/charge-points/:identity/config',
    tag: 'Configuration',
    summary: 'Change a configuration key',
    description:
      'Sends ChangeConfiguration to the charger and records the answer; the stored value changes only when the charger accepts. Needs charge_point:config or charge_point:command. SecurityProfile and AuthorizationKey are refused (use the keys endpoint), as are invalid values for catalogue keys and keys the charger reports as read-only (400). Returns 409 when the charger is offline.',
    pathParams: identityParam,
    body: {
      required: true,
      schema: ref('ConfigChangeRequest'),
      example: { key: 'HeartbeatInterval', value: '300' },
    },
    responses: { 200: { description: 'The charger answer.', schema: ref('ConfigChangeResult') } },
    errors: [400, 404, 409],
  },

  // ============================================================= OCPP 2.0.1 device model
  {
    method: 'GET',
    path: '/v1/charge-points/:identity/device-model',
    tag: 'Configuration',
    summary: 'Get the stored device model (OCPP 2.0.1)',
    description:
      'Returns what the station last reported about itself: components (with EVSE and connector) and their variables, each with attributes (Actual, Target, MinSet, MaxSet: value and mutability) and characteristics (data type, unit, limits, allowed values, whether it supports monitoring); the variable monitors; and the last ten report requests. Protected variables (SecurityCtrlr, network configuration) are flagged. supported is false for 1.6 chargers, whose settings are on the config endpoint. Does not contact the station.',
    pathParams: identityParam,
    responses: { 200: { description: 'The device model.', schema: { type: 'object', properties: {
      supported: { type: 'boolean' }, online: { type: 'boolean' }, variables: { type: 'integer' },
      components: { type: 'array', items: { type: 'object' } }, monitors: { type: 'array', items: { type: 'object' } }, reports: { type: 'array', items: { type: 'object' } },
    } } } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/device-model/report',
    tag: 'Configuration',
    summary: 'Ask the station for its device model (GetBaseReport)',
    description:
      'Sends GetBaseReport; the station answers with NotifyReport messages, which are stored as they arrive (the report\'s status moves from requested to receiving to complete). Needs charge_point:config or charge_point:command. 409 for a 1.6 or offline charger; 502 when the station does not answer.',
    pathParams: identityParam,
    body: { required: false, schema: { type: 'object', properties: { reportBase: { type: 'string', enum: ['FullInventory', 'ConfigurationInventory', 'SummaryInventory'], default: 'FullInventory' } } }, example: { reportBase: 'FullInventory' } },
    responses: { 200: { description: 'The station answer.', schema: { type: 'object', properties: { requestId: { type: 'integer' }, status: { type: 'string' }, state: { type: 'string', enum: ['requested', 'receiving', 'complete', 'rejected', 'empty'], description: 'Where the report stands: a quick station may already be sending it.' } } } } },
    errors: [400, 404, 409, 502],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/device-model/monitoring-report',
    tag: 'Configuration',
    summary: 'Ask the station for its variable monitors (GetMonitoringReport)',
    description:
      'Sends GetMonitoringReport; the NotifyMonitoringReport answer replaces the stored monitors. Same permissions and errors as the base report.',
    pathParams: identityParam,
    responses: { 200: { description: 'The station answer.', schema: { type: 'object', properties: { requestId: { type: 'integer' }, status: { type: 'string' }, state: { type: 'string' } } } } },
    errors: [404, 409, 502],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/device-model/get',
    tag: 'Configuration',
    summary: 'Read variables now (GetVariables)',
    description:
      'Reads 1 to 20 component/variable attributes from the station and stores the accepted values. Each result carries the station\'s attributeStatus (Accepted, Rejected, UnknownComponent, UnknownVariable, NotSupportedAttributeType).',
    pathParams: identityParam,
    body: {
      required: true,
      schema: { type: 'object', required: ['items'], properties: { items: { type: 'array', minItems: 1, maxItems: 20, items: { type: 'object', required: ['component', 'variable'], properties: {
        component: { type: 'string' }, componentInstance: { type: 'string' }, evseId: { type: 'integer' }, connectorId: { type: 'integer' },
        variable: { type: 'string' }, variableInstance: { type: 'string' }, attributeType: { type: 'string', enum: ['Actual', 'Target', 'MinSet', 'MaxSet'] },
      } } } } },
      example: { items: [{ component: 'OCPPCommCtrlr', variable: 'HeartbeatInterval' }] },
    },
    responses: { 200: { description: 'One result per item.', schema: { type: 'object', properties: { results: { type: 'array', items: { type: 'object' } } } } } },
    errors: [400, 404, 409, 502],
  },
  {
    method: 'PUT',
    path: '/v1/charge-points/:identity/device-model/variable',
    tag: 'Configuration',
    summary: 'Set a variable (SetVariables)',
    description:
      'Checks the value against what the station reported (data type, limits, allowed values, mutability) and sends SetVariables; the stored value changes when the station accepts (Accepted or RebootRequired). SecurityCtrlr variables, the network-connection priority and credentials are refused (400) — they have their own safe flows.',
    pathParams: identityParam,
    body: {
      required: true,
      schema: { type: 'object', required: ['component', 'variable', 'value'], properties: {
        component: { type: 'string' }, componentInstance: { type: 'string' }, evseId: { type: 'integer' }, connectorId: { type: 'integer' },
        variable: { type: 'string' }, variableInstance: { type: 'string' }, attributeType: { type: 'string', enum: ['Actual', 'Target', 'MinSet', 'MaxSet'], default: 'Actual' },
        value: { type: 'string' },
      } },
      example: { component: 'OCPPCommCtrlr', variable: 'HeartbeatInterval', value: '300' },
    },
    responses: { 200: { description: 'The station answer.', schema: { type: 'object', properties: { ok: { type: 'boolean' }, status: { type: 'string' }, rebootRequired: { type: 'boolean' }, reason: { type: 'string', nullable: true }, label: { type: 'string' } } } } },
    errors: [400, 404, 409, 502],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/device-model/monitors',
    tag: 'Configuration',
    summary: 'Add a variable monitor (SetVariableMonitoring)',
    description:
      'Asks the station to watch a variable: UpperThreshold / LowerThreshold (value is the limit), Delta (the change), Periodic / PeriodicClockAligned (seconds). Severity 0 (danger) to 9 (debug). A monitor that triggers sends NotifyEvent, which raises a charge_point.device_event alert; the alert resolves when the station reports the event cleared.',
    pathParams: identityParam,
    body: {
      required: true,
      schema: { type: 'object', required: ['component', 'variable', 'type', 'value', 'severity'], properties: {
        component: { type: 'string' }, componentInstance: { type: 'string' }, evseId: { type: 'integer' }, connectorId: { type: 'integer' },
        variable: { type: 'string' }, variableInstance: { type: 'string' },
        type: { type: 'string', enum: ['UpperThreshold', 'LowerThreshold', 'Delta', 'Periodic', 'PeriodicClockAligned'] },
        value: { type: 'number' }, severity: { type: 'integer', minimum: 0, maximum: 9 }, transaction: { type: 'boolean', default: false },
      } },
      example: { component: 'EVSE', evseId: 1, variable: 'Power', type: 'UpperThreshold', value: 22000, severity: 4 },
    },
    responses: { 200: { description: 'The station answer.', schema: { type: 'object', properties: { ok: { type: 'boolean' }, status: { type: 'string' }, id: { type: 'integer', nullable: true }, reason: { type: 'string', nullable: true } } } } },
    errors: [400, 404, 409, 502],
  },
  {
    method: 'DELETE',
    path: '/v1/charge-points/:identity/device-model/monitors/:monitorId',
    tag: 'Configuration',
    summary: 'Remove a variable monitor (ClearVariableMonitoring)',
    description: 'Clears the monitor on the station; the stored copy goes when the station answers Accepted or NotFound. Hard-wired monitors are refused by the station (Rejected).',
    pathParams: { ...identityParam, monitorId: 'The station\'s monitor id (an integer).' },
    responses: { 200: { description: 'The station answer.', schema: { type: 'object', properties: { ok: { type: 'boolean' }, status: { type: 'string' } } } } },
    errors: [400, 404, 409, 502],
  },

  // ============================================================= local list
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/local-list/sync',
    tag: 'RFID and tokens',
    summary: 'Push the local authorisation list to a charger',
    description:
      'Sends the organisation\'s offline-allowed cards (up to 1000) to the charger as a full SendLocalList update, so they keep working through a network outage. Refused with 400 when the charger is offline. A charger rejection is reported as ok false with a 200. Audited as token.local_list_synced.',
    pathParams: identityParam,
    responses: { 200: { description: 'Sync result.', schema: ref('LocalListSyncResult') } },
    errors: [400, 404],
  },
  {
    method: 'POST',
    path: '/v1/sites/:siteId/local-list/sync',
    tag: 'RFID and tokens',
    summary: 'Push the local authorisation list to every charger at a site',
    description:
      'Pushes the card list to each charge point at the site that is not decommissioned or pending adoption; offline units are skipped with error "offline". Returns one result per charger. Audited as token.local_list_synced.',
    pathParams: siteIdParam,
    responses: { 200: { description: 'Results per charger.', schema: ref('LocalListSiteSyncResult') } },
    errors: [404],
  },

  // ============================================================= tokens
  {
    method: 'GET',
    path: '/v1/tokens',
    tag: 'RFID and tokens',
    summary: 'List RFID cards',
    description:
      'Returns the organisation\'s cards (prepaid tokens excluded), most recently updated first, with lifetime usage totals.',
    query: [
      { name: 'q', description: 'Substring match on UID, holder name, fleet name or holder phone.', schema: { type: 'string' } },
      { name: 'status', description: 'Exact status, e.g. Accepted or Blocked.', schema: { type: 'string' } },
      { name: 'accountType', description: 'Account type.', schema: { type: 'string', enum: ['retail', 'fleet', 'vip', 'technician'] } },
      { name: 'limit', description: 'Maximum rows; default 500, at most 2000.', schema: { type: 'integer', minimum: 1, maximum: 2000, default: 500 } },
    ],
    responses: { 200: { description: 'Cards.', schema: arrayOf(ref('Token')) } },
  },
  {
    method: 'GET',
    path: '/v1/tokens/unknown',
    tag: 'RFID and tokens',
    summary: 'List recently presented unregistered cards',
    description:
      'Returns up to 20 idTags presented at your chargers in the last 30 minutes that are not registered, newest first, so an installer can tap a new card and pick it instead of typing its serial.',
    query: [{ name: 'identity', description: 'Only cards presented at this charge point.', schema: { type: 'string' } }],
    responses: { 200: { description: 'Unregistered cards.', schema: arrayOf(ref('TokenUnknownTag')) } },
  },
  {
    method: 'POST',
    path: '/v1/tokens',
    tag: 'RFID and tokens',
    summary: 'Register an RFID card',
    description:
      'Registers a card with holder, account type and limits; account type defaults to retail and status to Accepted. Invalid input is refused with 422, a UID already registered with 409. A PIN is stored hashed. Audited as token.issued.',
    body: {
      required: true,
      schema: { ...ref('TokenInput'), required: ['uid'] } as Schema,
      example: {
        uid: '04A2B9C1D25E80',
        holderName: 'Budi Santoso',
        holderPhone: '+62 812 3456 7890',
        accountType: 'fleet',
        fleetName: 'Bluebird Taxi Jakarta',
        validTo: '2027-12-31',
        energyLimitKwh: 5000,
        spendLimitIdr: 12500000,
        offlineAllowed: true,
      },
    },
    responses: { 200: { description: 'Registered.', schema: ref('TokenCreated') } },
    errors: [409, 422],
  },
  {
    method: 'PUT',
    path: '/v1/tokens/:id',
    tag: 'RFID and tokens',
    summary: 'Update an RFID card',
    description:
      'Changes only the fields sent; the UID cannot be changed. Setting a PIN resets the driver-app PIN lockout. After the response, roaming partners are told about the change. When the status changes, push the local list so offline chargers learn it. Audited as token.updated, or token.blocked when blocking.',
    pathParams: { id: 'Card id (UUID).' },
    body: {
      required: true,
      schema: ref('TokenInput'),
      example: { status: 'Blocked', notes: 'Reported lost by driver on 2026-09-20' },
    },
    responses: { 200: { description: 'Updated.', schema: ref('TokenUpdated') } },
    errors: [404, 422],
  },

  // ============================================================= tariffs
  {
    method: 'PUT',
    path: '/v1/sites/:siteId/tariff',
    tag: 'Tariffs',
    summary: 'Assign a tariff to a site',
    description:
      'Assigns one of your tariffs to the site, optionally for AC or DC connectors only, after checking it against the regulatory ceilings for the site\'s connectors. A tariff with a violation is refused with 409 and the flags; warnings are returned with a 200. Re-assigning the same tariff to the site replaces the earlier assignment. Audited as tariff.assigned.',
    pathParams: siteIdParam,
    body: {
      required: true,
      schema: ref('TariffAssignmentRequest'),
      example: { tariffId: '6f1c2a8e-3b4d-4e5f-9a1b-2c3d4e5f6a7b', priority: 10, currentType: 'DC' },
    },
    responses: { 200: { description: 'Assigned.', schema: ref('TariffAssignmentResult') } },
    errors: [404, 409],
  },
  {
    method: 'DELETE',
    path: '/v1/tariff-assignments/:id',
    tag: 'Tariffs',
    summary: 'Remove a tariff assignment',
    description: 'Deletes one assignment of one of your tariffs. Audited as tariff.unassigned.',
    pathParams: { id: 'Tariff assignment id (UUID).' },
    responses: { 200: { description: 'Removed.', schema: OK } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/tariffs/:id/archive',
    tag: 'Tariffs',
    summary: 'Archive a tariff',
    description:
      'Stops the tariff applying to new sessions from now; sessions it already priced keep it, so their invoices still reproduce. There is no delete. Returns 404 for an unknown or already archived tariff. Audited as tariff.archived.',
    pathParams: { id: 'Tariff id (UUID).' },
    responses: { 200: { description: 'Archived.', schema: OK } },
    errors: [404],
  },

  // ============================================================= sessions
  {
    method: 'GET',
    path: '/v1/sessions/search',
    tag: 'Sessions',
    summary: 'Search charging sessions',
    description:
      'Returns sessions newest first with the frozen CDR tax breakdown and the derived payment status, plus totals over all matching sessions. Site-scoped users see only their sites, masked cards and no holder names. Each filter may be given once; a bad siteId, from or to is refused with 400.',
    query: [
      ...sessionFilters,
      { name: 'limit', description: 'Page size; default 100, 1-500.', schema: { type: 'integer', minimum: 1, maximum: 500, default: 100 } },
      { name: 'offset', description: 'Rows to skip; default 0.', schema: { type: 'integer', minimum: 0, default: 0 } },
    ],
    responses: { 200: { description: 'Matching sessions.', schema: ref('SessionSearchResult') } },
    errors: [400],
  },
  {
    method: 'GET',
    path: '/v1/sessions.csv',
    tag: 'Sessions',
    summary: 'Export sessions as CSV',
    description:
      'Downloads up to 50,000 matching sessions as UTF-8 CSV with a byte-order mark (for Excel), including the tax breakdown. Cells that start with a formula character are prefixed to prevent formula injection; site-scoped users get masked cards. Each export is audited as session.exported.',
    query: sessionFilters,
    responses: {
      200: { description: 'CSV file (attachment).', contentType: 'text/csv', schema: { type: 'string' } },
    },
    errors: [400],
  },
  {
    method: 'GET',
    path: '/v1/sessions/:id/receipt',
    tag: 'Sessions',
    summary: 'Get a session receipt',
    description:
      'Returns a printable HTML tax receipt showing DPP, PPN and PBJT-TL separately, issued by the site owner when it is the seller of record and by the operator otherwise. An unrated session gets a receipt with a notice that no tax invoice can be issued yet. Site-scoped users see the card masked.',
    pathParams: { id: 'Session id (UUID).' },
    responses: { 200: { description: 'HTML receipt.', contentType: 'text/html', schema: { type: 'string' } } },
    errors: [404],
  },

  // ============================================================= load management
  {
    method: 'PUT',
    path: '/v1/sites/:siteId/power/priorities',
    tag: 'Load management',
    summary: 'Set connector load-management priorities',
    description:
      'Sets the priority of each listed connector (clamped to -100..100; higher wins under the priority strategy). Every connector must be at this site, or the request is refused with 400; entries before the bad one are applied. Audited as site.power_priorities.changed.',
    pathParams: siteIdParam,
    body: {
      required: true,
      schema: ref('CurtailPriorityList'),
      example: {
        priorities: [
          { connectorUuid: '0b7e4c2a-51d3-4f6e-8a9b-1c2d3e4f5a6b', priority: 50 },
          { connectorUuid: '9d8c7b6a-5e4f-4a3b-2c1d-0e9f8a7b6c5d', priority: 0 },
        ],
      },
    },
    responses: { 200: { description: 'Saved.', schema: OK } },
    errors: [400, 404],
  },
  {
    method: 'POST',
    path: '/v1/sites/:siteId/power/curtail',
    tag: 'Load management',
    summary: 'Curtail or release a site',
    description:
      'Curtailing (for a genset or grid outage) sends 0 W station limits to every charger at the site; releasing restores the normal allocation. The change is saved first and dispatched right after the response, so a dispatch failure never undoes it. Audited as site.curtailed or site.curtailment_lifted.',
    pathParams: siteIdParam,
    body: {
      required: true,
      schema: ref('CurtailRequest'),
      example: { curtailed: true, reason: 'PLN outage — running on genset' },
    },
    responses: { 200: { description: 'Saved; dispatch started.', schema: ref('CurtailResult') } },
    errors: [404],
  },

  // ============================================================= firmware
  {
    method: 'GET',
    path: '/v1/firmware/images',
    tag: 'Firmware and diagnostics',
    summary: 'List firmware images',
    description: 'Returns the organisation\'s firmware images, newest first, including archived ones.',
    responses: { 200: { description: 'Images.', schema: arrayOf(ref('FirmwareImage')) } },
  },
  {
    method: 'POST',
    path: '/v1/firmware/images',
    tag: 'Firmware and diagnostics',
    summary: 'Add a firmware image by URL',
    description:
      'Registers firmware hosted at a public HTTPS URL; chargers download it from there. URLs that resolve to private or internal addresses are refused. The declared SHA-256 is stored unverified until you call verify. Audited as firmware.image_added.',
    body: {
      required: true,
      schema: ref('FirmwareImageUrlRequest'),
      example: {
        name: 'Autel DC Fast 60 kW',
        version: 'V1.32.07',
        url: 'https://firmware.example-vendor.com/autel/dc60/V1.32.07.bin',
        vendor: 'Autel Energy',
        compatibleModels: ['MaxiCharger DC Fast'],
        sha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
        notes: 'Fixes CCS2 pre-charge timeout on Hyundai Ioniq 5',
      },
    },
    responses: { 200: { description: 'Added.', schema: ref('FirmwareImageCreated') } },
    errors: [400],
  },
  {
    method: 'POST',
    path: '/v1/firmware/images/upload',
    tag: 'Firmware and diagnostics',
    summary: 'Upload a firmware image',
    description:
      'Send the raw file as the request body with Content-Type application/octet-stream; the metadata (name, version, vendor, compatibleModels, sha256, notes, fileName) goes in the query string. The file is streamed to storage and hashed; files over the size cap (MAX_FIRMWARE_BYTES, 512 MiB by default) are refused with 413, and a declared sha256 that does not match is refused with 400 and the file discarded. Chargers download uploaded images from an unguessable URL on this deployment. Audited as firmware.image_uploaded.',
    query: [
      { name: 'name', required: true, description: 'Image name.', schema: { type: 'string', maxLength: 200 } },
      { name: 'version', required: true, description: 'The version string the charger will report after the update.', schema: { type: 'string', maxLength: 100 } },
      { name: 'vendor', description: 'Vendor.', schema: { type: 'string' } },
      { name: 'compatibleModels', description: 'Comma-separated model names a campaign may target.', schema: { type: 'string' } },
      { name: 'sha256', description: 'Declared SHA-256 (64 hex); the upload is refused if the file does not match.', schema: { type: 'string' } },
      { name: 'notes', description: 'Notes.', schema: { type: 'string', maxLength: 2000 } },
      { name: 'fileName', description: 'Stored file name (sanitised); defaults to {name}-{version}.bin.', schema: { type: 'string' } },
    ],
    body: {
      required: true,
      contentType: 'application/octet-stream',
      schema: { type: 'string', format: 'binary' },
      description: 'The firmware file.',
    },
    responses: { 200: { description: 'Uploaded.', schema: ref('FirmwareImageCreated') } },
    errors: [400, 413],
  },
  {
    method: 'POST',
    path: '/v1/firmware/images/:id/verify',
    tag: 'Firmware and diagnostics',
    summary: 'Verify a URL image checksum',
    description:
      'Downloads a URL-sourced image once on the server (through the same internal-address guard, up to the firmware size cap), hashes it and records the size and whether it matches the declared SHA-256. Nothing is stored. A failed download, uploaded image or mismatch returns 422. Audited as firmware.image_verified.',
    pathParams: { id: 'Firmware image id (UUID).' },
    responses: { 200: { description: 'Checksum verified.', schema: ref('FirmwareVerifyResult') } },
    errors: [404, 422],
  },
  {
    method: 'POST',
    path: '/v1/firmware/images/:id/archive',
    tag: 'Firmware and diagnostics',
    summary: 'Archive a firmware image',
    description:
      'Archives the image: new campaigns cannot use it and an uploaded file stops being served to chargers. Audited as firmware.image_archived.',
    pathParams: { id: 'Firmware image id (UUID).' },
    responses: { 200: { description: 'Archived.', schema: OK } },
    errors: [404],
  },
  {
    method: 'GET',
    path: '/v1/firmware/campaigns',
    tag: 'Firmware and diagnostics',
    summary: 'List firmware campaigns',
    description: 'Returns the organisation\'s campaigns, newest first, with job counts by outcome.',
    responses: { 200: { description: 'Campaigns.', schema: arrayOf(ref('CampaignSummary')) } },
  },
  {
    method: 'POST',
    path: '/v1/firmware/campaigns',
    tag: 'Firmware and diagnostics',
    summary: 'Create a firmware campaign',
    description:
      'Creates a job for each targeted charge point (fleet and site targets skip decommissioned and pending units). Refused with 422 when the input is invalid, the image is missing or archived, nothing matches, or any target is not a compatible model for the image. The scheduler dispatches jobs within about 30 seconds, only inside the maintenance window and only to online chargers. Audited as firmware.campaign_created.',
    body: {
      required: true,
      schema: ref('CampaignRequest'),
      example: {
        imageId: '3a9b8c7d-6e5f-4a1b-9c2d-8e7f6a5b4c3d',
        name: 'Autel DC60 V1.32.07 — Jakarta Pusat',
        targetType: 'site',
        targetIds: ['5c2f9e1a-7b3d-4c8e-a1f2-6d9b0e3c7a45'],
        windowStart: '01:00',
        windowEnd: '05:00',
        maxRetries: 3,
        retryIntervalS: 900,
      },
    },
    responses: { 200: { description: 'Created.', schema: ref('CampaignCreated') } },
    errors: [400, 422],
  },
  {
    method: 'GET',
    path: '/v1/firmware/campaigns/:id',
    tag: 'Firmware and diagnostics',
    summary: 'Get a firmware campaign',
    description: 'Returns the campaign, each charger job with its stage and connection state, and the stage names for a progress display.',
    pathParams: { id: 'Campaign id (UUID).' },
    responses: { 200: { description: 'The campaign.', schema: ref('CampaignDetail') } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/firmware/campaigns/:id/cancel',
    tag: 'Firmware and diagnostics',
    summary: 'Cancel a firmware campaign',
    description:
      'Cancels a scheduled or running campaign and its pending jobs; updates already sent to chargers are not recalled. Audited as firmware.campaign_cancelled.',
    pathParams: { id: 'Campaign id (UUID).' },
    responses: { 200: { description: 'Cancelled.', schema: OK } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/firmware/campaigns/:id/retry-failed',
    tag: 'Firmware and diagnostics',
    summary: 'Retry failed firmware jobs',
    description:
      'Resets every failed job to pending with zero attempts and sets the campaign back to running (unless it was cancelled). Audited as firmware.campaign_retried.',
    pathParams: { id: 'Campaign id (UUID).' },
    responses: {
      200: {
        description: 'Jobs reset.',
        schema: {
          type: 'object',
          properties: { ok: { type: 'boolean', const: true }, retried: { type: 'integer', description: 'Jobs reset.' } },
          required: ['ok', 'retried'],
        },
      },
    },
    errors: [404],
  },

  // ============================================================= diagnostics
  {
    method: 'GET',
    path: '/v1/charge-points/:identity/diagnostics',
    tag: 'Firmware and diagnostics',
    summary: 'List diagnostics requests',
    description:
      'Returns the last 100 log-upload requests for the charger, newest first. Site-scoped users do not see requests from before the charger joined their site.',
    pathParams: identityParam,
    responses: { 200: { description: 'Requests.', schema: arrayOf(ref('DiagnosticsRequestRow')) } },
    errors: [404],
  },
  {
    method: 'POST',
    path: '/v1/charge-points/:identity/diagnostics',
    tag: 'Firmware and diagnostics',
    summary: 'Request diagnostic logs',
    description:
      'Sends GetDiagnostics so the charger uploads its logs, either to your location or to a one-time URL on this deployment for the built-in log viewer. Needs charge_point:config or charge_point:command. Returns 409 when the charger is offline, and 422 (with the request id) when the location is invalid or the charger refuses or does not answer.',
    pathParams: identityParam,
    body: {
      required: false,
      schema: ref('DiagnosticsRequestBody'),
      example: { startTime: '2026-09-25T00:00:00+07:00', stopTime: '2026-09-26T00:00:00+07:00' },
    },
    responses: { 200: { description: 'Requested.', schema: ref('DiagnosticsRequested') } },
    errors: [404, 409, 422],
  },
  {
    method: 'GET',
    path: '/v1/diagnostics/:id/content',
    tag: 'Firmware and diagnostics',
    summary: 'Read an uploaded diagnostics log',
    description:
      'Returns the received log as text for the viewer: gzip is unpacked and text is capped at 2 MiB (truncated is then true); ZIP and other binary files are reported as binary with no text. available is false while no file has been received.',
    pathParams: { id: 'Diagnostics request id (UUID).' },
    responses: { 200: { description: 'Log content.', schema: ref('DiagnosticsContent') } },
    errors: [404],
    permissions: ['charge_point:read'],
  },
  {
    method: 'GET',
    path: '/v1/diagnostics/:id/download',
    tag: 'Firmware and diagnostics',
    summary: 'Download an uploaded diagnostics file',
    description: 'Returns the file exactly as the charger uploaded it, as an attachment. Returns 404 while no file has been received.',
    pathParams: { id: 'Diagnostics request id (UUID).' },
    responses: {
      200: { description: 'The file.', contentType: 'application/octet-stream', schema: { type: 'string', format: 'binary' } },
    },
    errors: [404],
    permissions: ['charge_point:read'],
  },

  // ============================================================= live events
  {
    method: 'GET',
    path: '/v1/events/frames',
    tag: 'Live events',
    summary: 'Stream raw OCPP frames',
    description:
      'Server-sent events: each new OCPP frame of your organisation (or of one charger) arrives as a data line holding a JSON object with id, ts, ocpp_identity, direction (in or out), message_type (2, 3 or 4), action, unique_id and payload. Frames are polled every 1.5 s, only frames after the connection opened are sent, and a comment ping keeps the stream alive every 25 s. Site-scoped users need charge_point:config or charge_point:command, because the log carries card idTags; read-only viewers get 403.',
    query: [{ name: 'identity', description: 'Only frames of this charge point.', schema: { type: 'string' } }],
    responses: { 200: { description: 'Event stream.', contentType: 'text/event-stream', schema: { type: 'string' } } },
    errors: [404],
  },
];
