// Mechanical rename *_idr → *_minor / *Idr → *Minor (docs/MULTI-COUNTRY-DESIGN.md §5.3, §6.1 WP1b).
//
//     npx tsx tools/codemods/idr-to-minor.mts            rewrite src/ and tools/ in place, list changed files
//     npx tsx tools/codemods/idr-to-minor.mts --dry      list what would change, write nothing
//     npx tsx tools/codemods/idr-to-minor.mts --sql      print migration 060's RENAME statements
//     npx tsx tools/codemods/idr-to-minor.mts --sql-down print the reverse (db/rollback/060_down.sql)
//
// Text-level and word-boundary based, longest names first, so it is idempotent:
// a second run changes nothing (every target name ends in Minor/_minor). Applies
// to .ts/.mts/.js/.html under src/ and tools/ (not this folder, not generated
// files: src/web/openapi.json and sdk/ are regenerated by `npm run openapi && npm run sdk`).
// Excluded: provider wire fields, env var names (upper case, never matched),
// config.tax.* / config.regulatory.* keys, the integration setting key
// postpayLimitIdr (stored in integration.settings; WP3), and the iOS Live
// Activity content-state keys costIdr / estimateIdr (an APNs wire contract with
// apps already installed; the Swift side changes with WP2).
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, extname } from 'node:path';

const root = join(import.meta.dirname, '..', '..');

/** §5.3: table → [old column, new column]. Generates 060 and drives the SQL renames. */
export const COLUMN_RENAMES: Array<[string, string, string]> = [
  ['cdr', 'subtotal_idr', 'subtotal_minor'],
  ['cdr', 'pbjt_rate_bps', 'local_tax_rate_bps'],
  ['cdr', 'pbjt_idr', 'local_tax_minor'],
  ['cdr', 'ppn_dpp_idr', 'tax_base_minor'],
  ['cdr', 'ppn_rate_bps', 'tax_rate_bps'],
  ['cdr', 'ppn_idr', 'tax_minor'],
  ['cdr', 'total_idr', 'total_minor'],
  ['site', 'pbjt_rate_bps', 'local_tax_rate_bps'],
  ['site', 'reservation_fee_idr', 'reservation_fee_minor'],
  ['site', 'v2x_credit_idr_per_kwh', 'v2x_credit_minor_per_kwh'],
  ['charging_session', 'prepaid_amount_idr', 'prepaid_amount_minor'],
  ['charging_session', 'v2x_credit_idr_per_kwh', 'v2x_credit_minor_per_kwh'],
  ['payment_intent', 'amount_authorised_idr', 'amount_authorised_minor'],
  ['payment_intent', 'amount_captured_idr', 'amount_captured_minor'],
  ['payment_intent', 'settlement_delta_idr', 'settlement_delta_minor'],
  ['payment_intent', 'refund_due_idr', 'refund_due_minor'],
  ['payment_intent', 'refunded_idr', 'refunded_minor'],
  ['payment_intent', 'hold_capture_idr', 'hold_capture_minor'],
  ['driver_charge', 'amount_idr', 'amount_minor'],
  ...(['driver_reservation', 'reservation_checkout'] as const).flatMap((t): Array<[string, string, string]> => [
    [t, 'fee_idr', 'fee_minor'],
    [t, 'fee_dpp_idr', 'fee_tax_base_minor'],
    [t, 'fee_ppn_idr', 'fee_tax_minor'],
    [t, 'fee_total_idr', 'fee_total_minor'],
  ]),
  ['fleet_invoice', 'subtotal_idr', 'subtotal_minor'],
  ['fleet_invoice', 'pbjt_idr', 'local_tax_minor'],
  ['fleet_invoice', 'tax_base_idr', 'taxable_minor'],
  ['fleet_invoice', 'dpp_idr', 'tax_base_minor'],
  ['fleet_invoice', 'ppn_idr', 'tax_minor'],
  ['fleet_invoice', 'own_total_idr', 'own_total_minor'],
  ['fleet_invoice', 'roaming_total_idr', 'roaming_total_minor'],
  ['fleet_invoice', 'total_idr', 'total_minor'],
  ['fleet_invoice', 'fees_total_idr', 'fees_total_minor'],
  ['fleet_invoice', 'credited_idr', 'credited_minor'],
  ['fleet_invoice', 'prior_credit_idr', 'prior_credit_minor'],
  ['fleet_credit_note', 'dpp_idr', 'tax_base_minor'],
  ['fleet_credit_note', 'ppn_idr', 'tax_minor'],
  ['fleet_credit_note', 'total_idr', 'total_minor'],
  ['commission_statement', 'gtv_idr', 'gtv_minor'],
  ['commission_statement', 'commission_idr', 'commission_minor'],
  ['commission_statement', 'minimum_topup_idr', 'minimum_topup_minor'],
  ['commission_statement', 'private_fee_idr', 'private_fee_minor'],
  ['commission_statement', 'mdr_credit_idr', 'mdr_credit_minor'],
  ['commission_statement', 'net_idr', 'net_minor'],
  ['commission_statement', 'ppn_idr', 'tax_minor'],
  ['commission_statement', 'total_idr', 'total_minor'],
  ['commission_statement', 'owner_share_idr', 'owner_share_minor'],
  ['subscription_plan', 'monthly_fee_idr', 'monthly_fee_minor'],
  ['subscription_plan', 'member_rate_idr', 'member_rate'],
  ['subscription_charge', 'fee_idr', 'fee_minor'],
  ['subscription_charge', 'dpp_idr', 'tax_base_minor'],
  ['subscription_charge', 'ppn_idr', 'tax_minor'],
  ['subscription_charge', 'total_idr', 'total_minor'],
  ['subscription_charge', 'credit_idr', 'credit_minor'],
  ['subscription_session', 'discount_idr', 'discount_minor'],
  ['promotion_redemption', 'discount_idr', 'discount_minor'],
  ['promotion', 'budget_idr', 'budget_minor'],
  ['loyalty_program', 'earn_per_1000_idr', 'earn_per_1000_minor'],
  ['loyalty_program', 'point_value_idr', 'point_value_minor'],
  ['loyalty_entry', 'value_idr', 'value_minor'],
  ['token', 'spend_limit_idr', 'spend_limit_minor'],
];

/** Check constraints whose names carry an old column name (renamed for hygiene). */
export const CONSTRAINT_RENAMES: Array<[string, string, string]> = [
  ['subscription_plan', 'subscription_plan_monthly_fee_idr_check', 'subscription_plan_monthly_fee_minor_check'],
  ['subscription_plan', 'subscription_plan_member_rate_idr_check', 'subscription_plan_member_rate_check'],
  ['fleet_credit_note', 'fleet_credit_note_dpp_idr_check', 'fleet_credit_note_tax_base_minor_check'],
  ['fleet_credit_note', 'fleet_credit_note_ppn_idr_check', 'fleet_credit_note_tax_minor_check'],
  ['fleet_credit_note', 'fleet_credit_note_total_idr_check', 'fleet_credit_note_total_minor_check'],
  ['subscription_charge', 'subscription_charge_credit_idr_check', 'subscription_charge_credit_minor_check'],
  ['loyalty_program', 'loyalty_program_earn_per_1000_idr_check', 'loyalty_program_earn_per_1000_minor_check'],
  ['loyalty_program', 'loyalty_program_point_value_idr_check', 'loyalty_program_point_value_minor_check'],
  ['site', 'site_reservation_fee_idr_check', 'site_reservation_fee_minor_check'],
  ['site', 'site_v2x_credit_idr_per_kwh_check', 'site_v2x_credit_minor_per_kwh_check'],
];

/** Snake-case names whose new name is not the generic `_idr → _minor`. Longest first when applied. */
export const SNAKE_MAP: Record<string, string> = {
  ppn_dpp_idr: 'tax_base_minor',
  fee_dpp_idr: 'fee_tax_base_minor',
  fee_ppn_idr: 'fee_tax_minor',
  tax_base_idr: 'taxable_minor',
  dpp_idr: 'tax_base_minor',
  ppn_idr: 'tax_minor',
  pbjt_idr: 'local_tax_minor',
  pbjt_rate_bps: 'local_tax_rate_bps',
  ppn_rate_bps: 'tax_rate_bps',
  member_rate_idr: 'member_rate',
  v2x_credit_idr_per_kwh: 'v2x_credit_minor_per_kwh',
};

/** camelCase names whose new name is not the generic `Idr → Minor`. */
export const CAMEL_MAP: Record<string, string> = {
  ppnDppIdr: 'taxBaseMinor',
  dppIdr: 'taxBaseMinor',
  ppnIdr: 'taxMinor',
  pbjtIdr: 'localTaxMinor',
  pbjtBaseIdr: 'localTaxBaseMinor',
  pbjtRateBps: 'localTaxRateBps',
  taxBaseIdr: 'taxableMinor',
  // A cost summary's taxes together (local tax + main tax); `taxMinor` is the main tax alone.
  taxIdr: 'taxTotalMinor',
  memberRateIdr: 'memberRate',
  energyRateIdr: 'energyRate',
  creditIdrPerKwh: 'creditMinorPerKwh',
  v2xCreditIdrPerKwh: 'v2xCreditMinorPerKwh',
};

/** Left alone everywhere. */
export const CAMEL_EXCLUDE = new Set([
  'estimateQrisMdrIdr', // an IDR-only estimate (QRIS MDR), name kept by design
  'roundingUnitIdr', 'idleFeeCapIdr', 'serviceFeeCeilingIdr', // config.tax.* / config.regulatory.*
  'postpayLimitIdr', // integration.settings key (stored); WP3 renames with a legacy read
]);

/** Left alone in these files only (wire contracts). */
const PER_FILE_EXCLUDE: Record<string, string[]> = {
  'src/services/live-activity.ts': ['costIdr', 'estimateIdr'],
  'src/services/live-activity.test.ts': ['costIdr', 'estimateIdr'],
  'src/services/brand.ts': ['costIdr', 'estimateIdr'],
  'src/services/brand.test.ts': ['costIdr', 'estimateIdr'],
  'tools/e2e/live-activity-e2e.mts': ['costIdr', 'estimateIdr'],
  // The Live Activity content state's wire names (v1.9 content version 2 keeps them; the amounts are in `currency`).
  'src/driver/mobile-api.test.ts': ['costIdr', 'estimateIdr'],
  'tools/e2e/mobile-api-e2e.mts': ['costIdr', 'estimateIdr'],
};

// multicountry/ holds the v1.6-side tools (golden fixtures, re-rate), written in v1.6's names on purpose.
const SKIP_DIRS = new Set(['node_modules', 'codemods', 'multicountry', '.git']);
const SKIP_FILES = new Set([
  'src/web/openapi.json',
  // These know both names on purpose (legacy reads and aliases).
  'src/domain/money.ts', 'src/domain/money.test.ts',
  'src/api/legacy-money.ts', 'src/api/legacy-money.test.ts',
  'src/services/tax/golden-id.test.ts', // replays v1.6 output, in v1.6's names
  'src/domain/country-literals.test.ts', // tests the codemod on v1.6 names
  // v1.5.0 compatibility tests: they assert the legacy names a v1.5 integration reads (docs/COMPATIBILITY-v1.5-to-v1.9.md)
  'src/api/openapi/compat-v15.test.ts', 'src/services/compat-v15.test.ts',
]);
const EXTS = new Set(['.ts', '.mts', '.js', '.html']);

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (EXTS.has(extname(name)) && !SKIP_FILES.has(relative(root, p))) out.push(p);
  }
  return out;
}

const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export interface RenameReport { changed: boolean; text: string; renames: Map<string, string>; collisions: string[] }

/** Rewrite one file's text. Pure; `rel` selects per-file exclusions. */
export function rewrite(text: string, rel = ''): RenameReport {
  const renames = new Map<string, string>();
  const keep = new Set([...CAMEL_EXCLUDE, ...(PER_FILE_EXCLUDE[rel] ?? [])]);
  const note = (from: string, to: string) => { renames.set(from, to); return to; };

  // Lines that talk ABOUT the old names (compatibility notes: "v1.6", "1.7",
  // "legacy", "deprecated") are left alone, so the codemod stays re-runnable over
  // code written after it.
  const lines = text.split('\n');
  const kept = new Map<number, string>();
  lines.forEach((l, i) => { if (/v1\.6|\b1\.7\b|legacy|deprecated/i.test(l)) kept.set(i, l); });

  // 1. explicit snake names, longest first
  let t = text;
  for (const k of Object.keys(SNAKE_MAP).sort((a, b) => b.length - a.length)) {
    t = t.replace(new RegExp(`\\b${esc(k)}\\b`, 'g'), () => note(k, SNAKE_MAP[k]!));
  }
  // 2. generic snake: lower-case identifiers only (env var names are upper case)
  t = t.replace(/\b([a-z][a-z0-9_]*)_idr\b/g, (m, base: string) => note(m, `${base}_minor`));
  // 3. explicit camel
  for (const k of Object.keys(CAMEL_MAP).sort((a, b) => b.length - a.length)) {
    if (keep.has(k)) continue;
    t = t.replace(new RegExp(`\\b${esc(k)}\\b`, 'g'), () => note(k, CAMEL_MAP[k]!));
  }
  // 4. generic camel
  t = t.replace(/\b([a-z][A-Za-z0-9]*)Idr\b/g, (m, base: string) => (keep.has(m) ? m : note(m, `${base}Minor`)));

  if (kept.size) {
    const out = t.split('\n');
    if (out.length === lines.length) for (const [i, l] of kept) out[i] = l;
    t = out.join('\n');
  }

  // Two different old names that now share one new name in the same file deserve a look
  // (e.g. dppIdr and ppnDppIdr both become taxBaseMinor).
  const byTarget = new Map<string, string[]>();
  for (const [from, to] of renames) byTarget.set(to, [...(byTarget.get(to) ?? []), from]);
  const collisions = [...byTarget].filter(([, froms]) => froms.length > 1).map(([to, froms]) => `${froms.join(' + ')} → ${to}`);
  return { changed: t !== text, text: t, renames, collisions };
}

/**
 * The rename statements as one guarded DO block: each rename runs only while the
 * old name exists, so the file can be applied again (or after a partial manual
 * repair) without error.
 */
function guardedRenames(cols: Array<[string, string, string]>, cons: Array<[string, string, string]>, title: string): string {
  const q = (x: string) => `'${x}'`;
  const colRows = cols.map(([t, a, b]) => `    ARRAY[${q(t)}, ${q(a)}, ${q(b)}]`).join(',\n');
  const conRows = cons.map(([t, a, b]) => `    ARRAY[${q(t)}, ${q(a)}, ${q(b)}]`).join(',\n');
  return `-- ${title}
DO $$
DECLARE r TEXT[];
BEGIN
  FOREACH r SLICE 1 IN ARRAY ARRAY[
${colRows}
  ] LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema() AND table_name = r[1] AND column_name = r[2]) THEN
      EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', r[1], r[2], r[3]);
    END IF;
  END LOOP;
  FOREACH r SLICE 1 IN ARRAY ARRAY[
${conRows}
  ] LOOP
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = r[2] AND conrelid = r[1]::regclass) THEN
      EXECUTE format('ALTER TABLE %I RENAME CONSTRAINT %I TO %I', r[1], r[2], r[3]);
    END IF;
  END LOOP;
END $$;
`;
}

export function sqlUp(): string {
  return guardedRenames(COLUMN_RENAMES, CONSTRAINT_RENAMES,
    'generated by tools/codemods/idr-to-minor.mts --sql (table, old, new); reviewed by hand');
}

export function sqlDown(): string {
  const flip = (l: Array<[string, string, string]>) => [...l].reverse().map(([t, a, b]): [string, string, string] => [t, b, a]);
  return guardedRenames(flip(COLUMN_RENAMES), flip(CONSTRAINT_RENAMES),
    'generated by tools/codemods/idr-to-minor.mts --sql-down (table, new, old)');
}

/** Files the codemod would still change (empty once it has run: it is idempotent). */
export function pendingChanges(): string[] {
  return [...walk(join(root, 'src')), ...walk(join(root, 'tools'))]
    .map((f) => relative(root, f))
    .filter((rel) => rewrite(readFileSync(join(root, rel), 'utf8'), rel).changed);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  if (args.includes('--sql')) process.stdout.write(sqlUp());
  else if (args.includes('--sql-down')) process.stdout.write(sqlDown());
  else {
    const dry = args.includes('--dry');
    let n = 0;
    for (const file of [...walk(join(root, 'src')), ...walk(join(root, 'tools'))]) {
      const rel = relative(root, file);
      const r = rewrite(readFileSync(file, 'utf8'), rel);
      if (!r.changed) continue;
      n++;
      console.log(`${dry ? 'would change' : 'changed'} ${rel} (${r.renames.size} names)`);
      for (const c of r.collisions) console.log(`  review: ${c}`);
      if (!dry) writeFileSync(file, r.text);
    }
    console.log(`${n} file(s) ${dry ? 'would change' : 'changed'}`);
  }
}
