import WebSocket from 'ws';
import { connect, boot, sleep, API, GW } from './lib.js';
import pg from 'pg';

const db = new pg.Pool({ connectionString: 'postgresql://postgres:plugsure@127.0.0.1:5432/plugsure_audit_a' });
const p = (s: string, v: any) => console.log(`  ${s.padEnd(52)} ${typeof v === 'string' ? v : JSON.stringify(v)}`);

async function main() {
  console.log('=== A. silent charger: boots then never heartbeats — ever marked offline? ===');
  const silent = await connect('AUDIT-SILENT-01');
  await boot(silent);
  await sleep(1000);
  let r = await db.query(`SELECT status, last_seen_at FROM charge_point WHERE ocpp_identity='AUDIT-SILENT-01'`);
  p('status right after boot', r.rows[0]);
  console.log('  ... waiting 20 s of total silence (heartbeat interval is 300 s) ...');
  await sleep(20000);
  r = await db.query(`SELECT status, last_seen_at, now()-last_seen_at AS age FROM charge_point WHERE ocpp_identity='AUDIT-SILENT-01'`);
  p('status after 20 s silence', r.rows[0]);
  p('any liveness sweeper in the codebase?', 'grep showed none — only ws close marks offline');
  // half-open socket: kill the TCP layer without a close frame
  (silent.ws as any)._socket.destroy();
  await sleep(3000);
  r = await db.query(`SELECT status FROM charge_point WHERE ocpp_identity='AUDIT-SILENT-01'`);
  p('status after the TCP socket was destroyed', r.rows[0]);
  const online = await fetch(`${API}/v1/charge-points`).then((x) => x.json()).catch(() => null);

  console.log('\n=== B. reconnect storm: 20 rapid reconnects ===');
  const t0 = Date.now();
  for (let i = 0; i < 20; i++) {
    const c = await connect('AUDIT-STORM-01');
    await boot(c);
    c.ws.terminate();
  }
  await sleep(2500);
  r = await db.query(`SELECT status, boot_count FROM charge_point WHERE ocpp_identity='AUDIT-STORM-01'`);
  p('after 20 connect/boot/terminate cycles', r.rows[0]);
  const fr = await db.query(`SELECT count(*)::int n FROM ocpp_frame WHERE ocpp_identity='AUDIT-STORM-01'`);
  p('ocpp_frame rows generated by the storm', fr.rows[0].n);
  p('elapsed ms', Date.now() - t0);

  console.log('\n=== C. two chargers, SAME identity, simultaneously ===');
  const c1 = await connect('AUDIT-TWIN-01');
  const c2 = await connect('AUDIT-TWIN-01');
  await boot(c1); await boot(c2);
  p('both sockets open?', [c1.ws.readyState === 1, c2.ws.readyState === 1]);
  // which one receives a command?
  let got1 = false, got2 = false;
  c1.onCall = () => { got1 = true; return { status: 'Accepted' }; };
  c2.onCall = () => { got2 = true; return { status: 'Accepted' }; };
  await fetch(`${API}/v1/charge-points/AUDIT-TWIN-01/commands/trigger`, {
    method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ requestedMessage: 'Heartbeat' }),
  }).catch(() => {});
  await sleep(800);
  p('command reached socket 1 / socket 2', [got1, got2]);
  // now close the FIRST (stale) one and see if the registry keeps the live one
  c1.ws.terminate();
  await sleep(800);
  r = await db.query(`SELECT status FROM charge_point WHERE ocpp_identity='AUDIT-TWIN-01'`);
  p('charge_point.status after the OLD socket closed', r.rows[0].status + '  (2nd socket still open)');
  let got2b = false;
  c2.onCall = () => { got2b = true; return { status: 'Accepted' }; };
  const cmd = await fetch(`${API}/v1/charge-points/AUDIT-TWIN-01/commands/trigger`, {
    method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ requestedMessage: 'Heartbeat' }),
  });
  await sleep(800);
  p('still commandable via the live socket?', `${got2b} (HTTP ${cmd.status})`);
  c2.close();

  console.log('\n=== D. charger that CALLERRORs every CSMS request ===');
  const bad = await connect('AUDIT-BADCP-01');
  bad.onCall = (action, payload, id) => {
    bad.ws.send(JSON.stringify([4, id, 'NotImplemented', 'nope', {}]));
    return undefined;
  };
  const tBad = Date.now();
  await boot(bad);
  await sleep(6000);
  p('provisioning survived a CALLERROR storm?', `socket open=${bad.ws.readyState === 1}, ${Date.now() - tBad} ms`);
  const badFrames = await db.query(`SELECT count(*)::int n FROM ocpp_frame WHERE ocpp_identity='AUDIT-BADCP-01'`);
  p('frames logged', badFrames.rows[0].n);
  bad.close();

  console.log('\n=== E. charger that NEVER replies to GetConfiguration ===');
  const mute = await connect('AUDIT-MUTE-01');
  mute.onCall = () => undefined; // never reply to anything
  const tMute = Date.now();
  await boot(mute);
  p('boot answered immediately (not blocked by provisioning)?', `${Date.now() - tMute} ms`);
  // can we still command it while provisioning is stuck?
  const t2 = Date.now();
  const resp = await fetch(`${API}/v1/charge-points/AUDIT-MUTE-01/commands/trigger`, {
    method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ requestedMessage: 'Heartbeat' }),
    signal: AbortSignal.timeout(20000),
  }).then((x) => `HTTP ${x.status}`).catch((e) => 'client gave up: ' + e.message);
  p('operator command issued while provisioning is stuck', `${resp} after ${Date.now() - t2} ms`);
  p('  (queued behind GetConfiguration; callTimeoutMs=30000)', '');
  mute.close();

  console.log('\n=== F. frame-log volume for one ordinary session ===');
  const before = (await db.query(`SELECT count(*)::int n FROM ocpp_frame`)).rows[0].n;
  const sess = await connect('AUDIT-VOL-01');
  sess.onCall = () => ({ status: 'Accepted' });
  await boot(sess);
  await sleep(2000);
  const afterProv = (await db.query(`SELECT count(*)::int n FROM ocpp_frame WHERE ocpp_identity='AUDIT-VOL-01'`)).rows[0].n;
  p('frames for boot + provisioning alone', afterProv);
  const tx = await sess.call('StartTransaction', { connectorId: 1, idTag: 'ID-RFID-0001', meterStart: 0, timestamp: new Date().toISOString() });
  for (let i = 1; i <= 30; i++) {
    await sess.call('MeterValues', {
      connectorId: 1, transactionId: tx.transactionId,
      meterValue: [{ timestamp: new Date().toISOString(), sampledValue: [
        { value: String(i * 300), measurand: 'Energy.Active.Import.Register', unit: 'Wh' },
        { value: '7400', measurand: 'Power.Active.Import', unit: 'W' },
        { value: '32', measurand: 'Current.Import', unit: 'A' },
        { value: '230', measurand: 'Voltage', unit: 'V' },
        { value: '61', measurand: 'SoC', unit: 'Percent' }] }],
    });
  }
  await sess.call('StopTransaction', { transactionId: tx.transactionId, meterStop: 9000, timestamp: new Date().toISOString(), reason: 'Local' });
  await sleep(1000);
  const afterSess = (await db.query(`SELECT count(*)::int n FROM ocpp_frame WHERE ocpp_identity='AUDIT-VOL-01'`)).rows[0].n;
  const bytes = await db.query(`SELECT sum(pg_column_size(payload))::int b FROM ocpp_frame WHERE ocpp_identity='AUDIT-VOL-01'`);
  p('frames after a 30-sample session (1-min samples = 30 min)', afterSess);
  p('payload bytes for that one charge point', bytes.rows[0].b);
  p('extrapolated rows/charger/day at 1-min MeterValues', Math.round((afterSess - afterProv) / 31 * 1440));
  sess.close();

  console.log('\n=== G. frame log is fire-and-forget: does a DB failure surface? ===');
  p('src/ocpp/server.ts:220', '.catch(() => {})  — every frame-log write error is swallowed silently');

  await db.end(); process.exit(0);
}
main().catch((e) => { console.error('FATAL', e); process.exit(1); });
